### ISSUE TITLE
IBC not logging into gateway 

### ISSUE THREAD

**Issue by CalebBrody** [IbcAlpha/IBC#102]
Hi. I set my username and password in the config file but when I try to log in I get stuck at the login window. I tried running manually with 
ibcstart.sh 981 -g --tws-path=/home/ec2-user/Jts --tws-settings-path= --ibc-path=/opt/ibc --ibc-ini=/home/ec2-user/ibc/config.ini --user=[user] --pw=[pass] --fix-user= --fix-pw= --java-path= --mode=paper  --on2fatimeout=exit 
but even then I get
IBC: IBC closing after TWS/Gateway failed to display login dialog

**Comment by rlktradewright** [comment]
Please run it again using the gatewaystart.sh script. Then attach the IBC log file to your reply. Please attach the whole log file.

In case you don't know, you attach a file by dragging it to the box at the bottom of the comment box.

**Comment by CalebBrody** [comment]
Hey, I switched from Centos to Ubuntu and It's working. Closing ticket
