### ISSUE TITLE
Can we use IBC to It automatically fills in username password for Client Portal API? 

### ISSUE THREAD

**Issue by AshiHarel** [IbcAlpha/IBC#103]
Hi, 

According to the docs IBC can be used for automating log in process in TWS as well as the Gateway. 
But im puzzled if its the gateway only for **Trader Workstation (TWS) API** , or I can use it also for  **Client Portal API** ? 

Please see: 
https://www.interactivebrokers.com/en/index.php?f=5041
for more info as for the difference between the two. 

Thanks, 
Ashi

**Comment by rlktradewright** [comment]
No, the client portal and its API are completely different and nothing whatever to do with TWS or Gateway. It's a web-based service that does not involve a locally running instance of TWS or Gateway. 

IBC cannot log in to the Client Portal for you.

**Comment by AshiHarel** [comment]
Thanks

**Comment by tredondo** [comment]
There's a different project for headless/unattended login to the InteractiveBrokers Client Portal Web API Gateway, @Voyz's [IBeam](https://github.com/Voyz/ibeam).
