### ISSUE TITLE
 Paper trading - "I understand and accept" dialog not closing

### ISSUE THREAD

**Issue by pedritolo** [IbcAlpha/IBC#106]
Hi, thanks for such a useful tool!

Maybe I'm doing something wrong, but as the title says, upon a successful login on paper trading, the dialog - "I understand and accept" isn't closing.
Thanks in advance

[config.ini](https://github.com/IbcAlpha/IBC/files/5743491/config.ini.txt)
[IBC-3.8.4-beta.2_GATEWAY-978_SATURDAY.txt](https://github.com/IbcAlpha/IBC/files/5743492/IBC-3.8.4-beta.2_GATEWAY-978_SATURDAY.txt)

IB Gateway
build 978.2i, Nov 13, 2020 11:47:06 AM 
Jolt Build 1.14.1, Nov 22, 2019 02:32:27 PM 
Nia Build 2.20.2, Jan 22, 2020 04:13:16 PM 
ModelNav Build 1.11.0, Sep 20, 2019 06:06:15 PM 
Riskfeed Build 2.38.6, May 13, 2020 09:21:47 AM  
Java Version: 1.8.0_152, OS: Windows 10 (amd64, 10.0), Memory: heap max 768Mb, current 40Mb

**Comment by rlktradewright** [comment]
See the note for this setting in config.ini:

`AcceptNonBrokerageAccountWarning`

**Comment by pedritolo** [comment]
Very nice, somehow I missed that!

thanks a ton, man, and happy holidays

p.s. Small remark, the description for that entry says the default value is "yes", but it actually is "no" atm

**Comment by rlktradewright** [comment]
No that's not right, the default is `yes`.

Read the comments at the start of config.ini. It says:

```
# When referred to below, the default value for a setting is the value
# assumed if either the setting is included but no value is specified, or
# the setting is not included at all.
#
```
Don't confuse the default setting with the setting that happens to be in config.ini 'out-of-the-box'. They are not the same thing.
