### ISSUE TITLE
can IBC set time zone?

### ISSUE THREAD

**Issue by tbrown122387** [IbcAlpha/IBC#110]
Can the timezone be set by IBC?

I try changing `jts.ini`, but after I log in, it gets changed back to `TimeZone=Africa/Abidjan`.

I've been searching around, and all I've found on the matter is [this](https://github.com/IbcAlpha/IBC/issues/60).

**Comment by rlktradewright** [comment]
NO, IBC can't set the timezone.

But the issue you referred to tells you what to do. You don't say whether you tried following that, and if so what happened.

**Comment by tbrown122387** [comment]
I didn’t try. I rather just change it after I pull the data into R/Python
