### ISSUE TITLE
gateway.sh not running from crontab on headless machine. 

### ISSUE THREAD

**Issue by rorymac** [IbcAlpha/IBC#111]
Hello 

Running Mint Linux 20
IB gateway 978 
IBC/Alpha 3.8.3 

My crontab is using your command : 
` 0,15,30,45 * * * 1-5 export DISPLAY=:0 && /bin/bash /opt/ibc/gatewaystart.sh `

I have checked the DISPLAY variable using echo $DISPLAY 
 
If I am logged into the GUI in Mint then IBC will log me into the gateway using the two factor authorisation.

If I try and run the machine headless it appears not to run the shell script. 
well concretely, I get no attempt from two factor from IB to log in. 

So not entirely sure if that is how it works? 
or can it work with a headless machine? 
 or does mean a different DISPLAY variable?

**Comment by shevkoplyas** [comment]
Hey Rory,

Try this tutorial:
[How to setup IBC (3.8.1) + TWS (build 976) on headless Ubuntu 18.04 LTS to run TWO accounts (paper + real) in 10 minutes](https://dimon.ca/how-to-setup-ibc-and-tws-on-headless-ubuntu-in-10-minutes/)

The headless environment can be harsh.. Also when you run stuff from the crontab - it is different PATH (and different other environment values) compared to when you logged in. It is different user => different permission outcomes for different users. Or something simple like "missing end of line" at the end of your crontab - there can be many reasons for stuff to not work properly.
Ideally you shouldn't even use the crontab, but instead register your task as a systemd service and control it using simple start / stop commands (systemd services allow you great deal of required environments, as well as dependencies on other services etc. It is much nicer than an attempt to squeeze everything into 1-liner (too hacky:))
If you don't want to keep things running 24/7 you can optionally use crontab to kickstart and/or stop the service.

Cheeers,
Dmitry

**Comment by rorymac** [comment]
Dmitry 
Thank you!
