### ISSUE TITLE
ibcstart.sh MacOS Errors

### ISSUE THREAD

**Issue by sdudley-bsc** [IbcAlpha/IBC#114]
The file paths on lines 254 and 263:
tws_vmoptions=${tws_path}/Trader Workstation ${tws_version}/tws.vmoptions
gateway_vmoptions=${tws_path}/IB Gateway ${tws_version}/ibgateway.vmoptions

should be enclosed in double quotes.

**Comment by rlktradewright** [comment]
Oh dear me, I'm an eejit!

Will fix.
