### ISSUE TITLE
ib-gateway paper trading warning at startup

### ISSUE THREAD

**Issue by pserguei** [IbcAlpha/IBC#119]
Hello,

I am using IBC 3.8.5 and IB-Gateway 981.
One issue I have is - when starting IB-Gateway with IBC in paper trading mode - I get a warning from IB-gateway (attached), and unless I manually hit "agree" button - I can't use IBKR APIs.
Is there any way in IBC to emulate this agree warning confirmation, or may be, I  have missed some settings in the IB-gateway itself.
Please, help.

Thanks in advance, Serguei.

![warning](https://user-images.githubusercontent.com/84237095/118364648-4c391380-b567-11eb-9fc3-bedab40a0a47.png)

**Comment by rlktradewright** [comment]
Look at the `AcceptNonBrokerageAccountWarning` setting in config.ini.

**Comment by pserguei** [comment]
Perfect ! 
Thank you very much !
