### ISSUE TITLE
Use %USERPROFILE% instead of %HOMEDRIVE%%HOMEPATH%

### ISSUE THREAD

**Issue by dmytro-sheyko** [IbcAlpha/IBC#124]
The fact is that such env vars as `HOMEDRIVE` and `HOMEPATH` are not set in all circumstances. When IBC is started from Task Scheduler on behalf of user that is not logged in, these variables are empty. However, `USERPROFILE` seems work in all cases. So I would propose to use `%USERPROFILE%` instead of `%HOMEDRIVE%%HOMEPATH%` to locate `config.ini` by default.

**Comment by rlktradewright** [comment]
Thanks for spotting that Dmitry. 

It seems pretty weird to me that %HOMEDRIVE% and %HOMEPATH% aren't set under those circumstances , but I've confirmed that you're right. I'll merge the PR.
