### ISSUE TITLE
xterm: not found

### ISSUE THREAD

**Issue by HINEOWAKEUP** [IbcAlpha/IBC#13]
/opt/ibc# ./gatewaystart.sh: 173: ./gatewaystart.sh: xterm: not found

my OS is GUI'less, anyone give a step-by-steps instruction to prepare that?
Thanks!

**Comment by rlktradewright** [comment]
You need to use something like [xvfb](https://en.wikipedia.org/wiki/Xvfb).

If you look at Issue #10 and search for 'xvfb' you'll find some further hints.

**Comment by micheloosterhof** [comment]
You can run `gatewaystart.sh` with the `-inline` parameter to avoid the xterm.
You will still need something like `xvfb`, but you won't have to install xterm.
