### ISSUE TITLE
Feature: Suppress "Navigating away from <ticker> will reset the order entry." warning

### ISSUE THREAD

**Issue by stenri** [IbcAlpha/IBC#136]
I propose to add a new SuppressNavigatingAwayWarning option which allows a user to suppress "Navigating away from <ticker> will reset the order entry." warning.

When user changes Order Type, Quantity or other fields in Order Entry dialog and switches to a different ticker, TWS displays dialog box with a warning:

There are many questions in the internet how to disable this warning, and unfortunately, TWS does not have built-in option to turn it off. See:

https://www.reddit.com/r/interactivebrokers/comments/m2ugqk/remove_navigating_away_popup_message/

https://www.elitetrader.com/et/threads/tws-2-specific-questions-remove-from-for-you-and-disable-order-entry-reset.355898/

I myself find this warning very annoying. So I developed a patch to add SuppressNavigatingAwayWarning option to IBC:

```
# Suppress Navigating Away Warning
# --------------------------------
#
# If you change Order Type, Quantity or other fields in Order Entry
# dialog and switch to a different ticker in a linked window, 
# TWS displays dialog box with a warning:
#
# "Navigating away from <ticker> will reset the order entry." 
#
# TWS doesn't have built-in option to disable this warning.
#
#   yes   means the dialog is dismissed as though the user had
#         clicked the 'Continue' button: this means that you accept
#         Order Entry fields are reset to default values while
#         switching to different ticker.
#
#   no    means the dialog remains on display and must be
#         handled by the user.

SuppressNavigatingAwayWarning=no
```
See my pull request below.

**Comment by rlktradewright** [comment]
I'm currently working on a generic way of dealing with this sort of annoying dialog. This will involve a new setting in config.ini which will describe how to recognise such dialogs and what action to take. Once this is implemented, handling these dialogs will not involve any new code, just a matter of editing config.ini and restarting.

It'll probably be a week or two before this is ready (I'm not finding much time for working on IBC at the moment), so would you mind waiting for that.

**Comment by stenri** [comment]
Ok, thanks for letting me know! I'm not in a hurry and can wait till you release a generic feature since I have a solution that works for me right now.
