### ISSUE TITLE
new dislog : Untrusted Connection

### ISSUE THREAD

**Issue by wsj3000** [IbcAlpha/IBC#138]
I use TWS 9.78 and IBC 3.9, sometimes it pop up a window : Untrusted Connection. If I do not click the button " I understand the risks - continue login", it seems TWS will lost its connection to server a mount later. Any body else met this problem ? please help to analysis, thanks a lot. 

the log from ibc-3.9.0_TWS-978_Friday.txt:

2021-09-04 04:49:12:291 IBC: Detected frame entitled: Connecting to server...; event=Activated
2021-09-04 04:49:12:292 IBC: Detected frame entitled: Connecting to server...; event=Focused
2021-09-04 04:49:24:980 IBC: Detected dialog entitled: Untrusted Connection; event=Opened

null(javax.swing.JRootPane){Object.Component.Container.JComponent.JRootPane}
|   null.glassPane(javax.swing.JPanel){Object.Component.Container.JComponent.JPanel}
|   null.layeredPane(javax.swing.JLayeredPane){Object.Component.Container.JComponent.JLayeredPane}
|   |   null(javax.swing.JPanel){Object.Component.Container.JComponent.JPanel}
|   |   |   null(twslaunch.jconnection.ssl.y){Object.Component.Container.JComponent.Box.y}
|   |   |   |   null(javax.swing.JLabel){JLabel: The connection to mcgw1_hb1.ibllc.com.cn is untrusted}
|   |   |   |   null(twslaunch.jconnection.ssl.z){Object.Component.Container.JComponent.z}
|   |   |   |   null(javax.swing.Box$Filler){Object.Component.Container.JComponent.Filler}
|   |   |   |   null(javax.swing.JLabel){JLabel: • The host name does not match the certificate}
|   |   |   |   null(javax.swing.Box$Filler){Object.Component.Container.JComponent.Filler}
|   |   |   |   null(javax.swing.JTextPane){Object.Component.Container.JComponent.JTextComponent.JEditorPane.JTextPane}
|   |   |   null(javax.swing.JPanel){Object.Component.Container.JComponent.JPanel}
|   |   |   |   null(javax.swing.JButton){JButton: I understand the risks - continue login}
|   |   |   |   null(javax.swing.JButton){JButton: Cancel}
|   |   null(javax.swing.JPanel){Object.Component.Container.JComponent.JPanel}
|   |   |   null(jtscomponents.plaf.dV){Object.Component.Container.JComponent.JPanel.dV}
|   |   null(jtscomponents.plaf.dT){Object.Component.Container.JComponent.JPanel.dT}
|   |   |   null(javax.swing.JLabel){JLabel: }
|   |   |   null(javax.swing.JLabel){JLabel: UNTRUSTED CONNECTION}
|   |   |   null(javax.swing.JLabel){JLabel: }
|   |   |   null(jtscomponents.plaf.dy){JButton: }
|   |   |   null(jtscomponents.plaf.dR){Object.Component.Container.JComponent.JPanel.dR}
|   |   |   Close(jtscomponents.plaf.dm){JButton: }
|   |   |   Maximize(jtscomponents.plaf.dn){JButton: }
|   |   |   Minimize(jtscomponents.plaf.dm){[Disabled]JButton: }

2021-09-04 04:49:25:120 IBC: Detected frame entitled: Attempt 4: connecting to server...; event=Lost focus
2021-09-04 04:49:25:121 IBC: Detected frame entitled: Attempt 4: connecting to server...; event=Deactivated

**Comment by rlktradewright** [comment]
I suggest you upgrade to the current stable version of TWS, which is version 981.3c.

If the problem still occurs, you should contact IB to find out why this is happening.

I don't think this is something IBC should automate until we have a clear understanding of what it really means and why it happens.

It might also help if you attach (not quote) your IBC logfile - all of it please.

**Comment by wsj3000** [comment]
> I suggest you upgrade to the current stable version of TWS, which is version 981.3c.
> 
> If the problem still occurs, you should contact IB to find out why this is happening.
> 
> I don't think this is something IBC should automate until we have a clear understanding of what it really means and why it happens.
> 
> It might also help if you attach (not quote) your IBC logfile - all of it please.

OK, I have contact IB. the server of HongKong has this problem and they was working on it. Thank you very much~~
