### ISSUE TITLE
Warning Dialog in TWS Paper trading mode

### ISSUE THREAD

**Issue by Girish400** [IbcAlpha/IBC#139]
Hi Richard,

Thank you for maintaining and having IBC on GitHub. Your efforts are highly appreciated. 

I had a feature request. If you feel this feature will add value to IBC, can you please incorporate the feature request in IBC.

While using IBC for autologin TWS in paper account, TWS throws a warning dialog mentioning this is not a brokerage account.

Can IBC click and automatically accept "I understand and accept" button? I understand this dialog is important, because if this 

warning is not presented, many people will make mistakes of using paper account as live account or vice versa. So if you decide 

to make this change we can have a setting to suppress the warning dialog based on shell script (StartTWS.bat)

Thank you,
Girish

**Comment by rlktradewright** [comment]
Please explain why the `AcceptNonBrokerageAccountWarning` setting in config.ini doesn't meet your requirement?

**Comment by Girish400** [comment]
My Bad. I'm very sorry for not looking into this.

Thank you for taking time and responding to this thread
