### ISSUE TITLE
Which version of TWS should  be used

### ISSUE THREAD

**Issue by jlitz** [IbcAlpha/IBC#144]
I installed the lastest standalone version of TWS 10.10.2p  from https://www.interactivebrokers.com/en/index.php?f=15875  But keep getting error message:  Error: Offline TWS/Gateway version 10.10 is not installed: can't find jars folder 
       Make sure you install the offline version of TWS/Gateway
       IBC does not work with the auto-updating TWS/Gateway

TWS was installed to and the correct path is set in .ini to C:\jts\1010  its labeled as an offline version

**Comment by rlktradewright** [comment]
Set the major version variable in StartTws.bat to 1010, not to 10.10

**Comment by jlitz** [comment]
same error  with 1010 not installed instead

set TWS_MAJOR_VRSN=1010
set C:\IBController\config.ini
set TRADING_MODE=live
set TWOFA_TIMEOUT_ACTION=exit
set IBC_PATH=C:\ibcontroller
set TWS_PATH=C:\jts\1010
set TWS_SETTINGS_PATH=c:\jts
set LOG_PATH=c:\ibcontroller\Logs
set TWSUSERID=xxxxx
set TWSPASSWORD=xxxxx
set JAVA_PATH=C:\jts
set HIDE=

**Comment by rlktradewright** [comment]
TWS_PATH should be C:\Jts. This variable has never included the version number.

**Comment by rlktradewright** [comment]
Also, why have you got IBController appearing in your .bat file?

Please take some time to review your settings carefully, otherwise you're just wasting my time.

**Comment by jlitz** [comment]
Do not  mean to waste your time  I'm just an old fart a  bit slow
seems to be working now other than inserting User and PW
log:

================================================================================

Starting IBController version 3.4.0 on Sun 10/03/2021 at 13:38:11.54

Operating system:  Microsoft Windows 10 Home  64-bit          10.0.19043  


Arguments:

TWS version = 1010
Entry point = ibcontroller.IBController
/TwsPath = C:\Jts
/IbcPath = C:\IBC
/IbcIni = C:\IBC\IBcontroller.ini
/Mode = live
/JavaPath = 
/User = ***
/PW = ***
/FIXUser =
/FIXPW =

=================================

Generating the classpath
Classpath=C:\Jts\1010\jars\jts4launch-1010.jar;C:\Jts\1010\jars\jxbrowser-7.17.jar;C:\Jts\1010\jars\jxbrowser-swing-7.17.jar;C:\Jts\1010\jars\jxbrowser-win64-7.17.jar;C:\Jts\1010\jars\locales.jar;C:\Jts\1010\jars\log4j-api-2.12.0.jar;C:\Jts\1010\jars\log4j-core-2.12.0.jar;C:\Jts\1010\jars\total-2020.jar;C:\Jts\1010\jars\twslaunch-1010.jar;C:\Jts\1010\jars\twslaunch-install4j-1.10.jar;C:\IBC\IBController.jar

Generating the JAVA VM options
Java VM Options= -Xmx768m -XX:+UseG1GC -XX:MaxGCPauseMillis=200 -XX:ParallelGCThreads=20 -XX:ConcGCThreads=5 -XX:InitiatingHeapOccupancyPercent=70 -Dinstaller.uuid=4304bcb2-10c2-44eb-b7a6-a74cb5fcdd7c -DvmOptionsPath=C:\Jts\1010\tws.vmoptions -Dsun.awt.nopixfmt=true -Dsun.java2d.noddraw=true -Dswing.boldMetal=false -Dsun.locale.formatasdefault=true

Determining the location of java.exe 
Location of java.exe=c:\users\jlitw\.i4j_jres\1.8.0_152-tzdata2019c_64\bin

Starting IBController with this command:
"c:\users\jlitw\.i4j_jres\1.8.0_152-tzdata2019c_64\bin\java.exe" -cp  "C:\Jts\1010\jars\jts4launch-1010.jar;C:\Jts\1010\jars\jxbrowser-7.17.jar;C:\Jts\1010\jars\jxbrowser-swing-7.17.jar;C:\Jts\1010\jars\jxbrowser-win64-7.17.jar;C:\Jts\1010\jars\locales.jar;C:\Jts\1010\jars\log4j-api-2.12.0.jar;C:\Jts\1010\jars\log4j-core-2.12.0.jar;C:\Jts\1010\jars\total-2020.jar;C:\Jts\1010\jars\twslaunch-1010.jar;C:\Jts\1010\jars\twslaunch-install4j-1.10.jar;C:\IBC\IBController.jar"  -Xmx768m -XX:+UseG1GC -XX:MaxGCPauseMillis=200 -XX:ParallelGCThreads=20 -XX:ConcGCThreads=5 -XX:InitiatingHeapOccupancyPercent=70 -Dinstaller.uuid=4304bcb2-10c2-44eb-b7a6-a74cb5fcdd7c -DvmOptionsPath=C:\Jts\1010\tws.vmoptions -Dsun.awt.nopixfmt=true -Dsun.java2d.noddraw=true -Dswing.boldMetal=false -Dsun.locale.formatasdefault=true ibcontroller.IBController "C:\IBC\IBcontroller.ini" "***" "***" live

System Properties
------------------------------------------------------------
swing.boldMetal = false
java.runtime.name = Java(TM) SE Runtime Environment
sun.boot.library.path = c:\users\jlitw\.i4j_jres\1.8.0_152-tzdata2019c_64\bin
java.vm.version = 25.152-b16
sun.awt.nopixfmt = true
vmOptionsPath = C:\Jts\1010\tws.vmoptions
java.vm.vendor = Oracle Corporation
java.vendor.url = http://java.oracle.com/
path.separator = ;
java.vm.name = Java HotSpot(TM) 64-Bit Server VM
file.encoding.pkg = sun.io
user.country = US
user.script = 
sun.java.launcher = SUN_STANDARD
sun.os.patch.level = 
java.vm.specification.name = Java Virtual Machine Specification
user.dir = C:\Jts
java.runtime.version = 1.8.0_152-b16
java.awt.graphicsenv = sun.awt.Win32GraphicsEnvironment
java.endorsed.dirs = c:\users\jlitw\.i4j_jres\1.8.0_152-tzdata2019c_64\lib\endorsed
os.arch = amd64
java.io.tmpdir = C:\WINDOWS\TEMP\
line.separator = 

java.vm.specification.vendor = Oracle Corporation
user.variant = 
os.name = Windows 10
sun.java2d.noddraw = true
sun.jnu.encoding = Cp1252
java.library.path = c:\users\jlitw\.i4j_jres\1.8.0_152-tzdata2019c_64\bin;C:\WINDOWS\Sun\Java\bin;C:\WINDOWS\system32;C:\WINDOWS;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Users\jlitw\AppData\Roaming\ActiveState\bin;C:\windows\system32;C:\windows;C:\windows\System32\Wbem;C:\windows\System32\WindowsPowerShell\v1.0\;C:\windows\System32\OpenSSH\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files (x86)\Common Files\Intel\Shared Libraries\redist\intel64_win\compiler;C:\Users\jlitw\AppData\Local\Microsoft\WindowsApps;;.
java.specification.name = Java Platform API Specification
java.class.version = 52.0
sun.management.compiler = HotSpot 64-Bit Tiered Compilers
os.version = 10.0
user.home = C:\Users\jlitw
user.timezone = America/New_York
installer.uuid = 4304bcb2-10c2-44eb-b7a6-a74cb5fcdd7c
java.awt.printerjob = sun.awt.windows.WPrinterJob
file.encoding = Cp1252
java.specification.version = 1.8
java.class.path = C:\Jts\1010\jars\jts4launch-1010.jar;C:\Jts\1010\jars\jxbrowser-7.17.jar;C:\Jts\1010\jars\jxbrowser-swing-7.17.jar;C:\Jts\1010\jars\jxbrowser-win64-7.17.jar;C:\Jts\1010\jars\locales.jar;C:\Jts\1010\jars\log4j-api-2.12.0.jar;C:\Jts\1010\jars\log4j-core-2.12.0.jar;C:\Jts\1010\jars\total-2020.jar;C:\Jts\1010\jars\twslaunch-1010.jar;C:\Jts\1010\jars\twslaunch-install4j-1.10.jar;C:\IBC\IBController.jar
user.name = jlitw
java.vm.specification.version = 1.8
sun.java.command = ibcontroller.IBController C:\IBC\IBcontroller.ini beach294 stpete77 live
java.home = c:\users\jlitw\.i4j_jres\1.8.0_152-tzdata2019c_64
sun.arch.data.model = 64
user.language = en
java.specification.vendor = Oracle Corporation
awt.toolkit = sun.awt.windows.WToolkit
java.vm.info = mixed mode
java.version = 1.8.0_152
java.ext.dirs = c:\users\jlitw\.i4j_jres\1.8.0_152-tzdata2019c_64\lib\ext;C:\WINDOWS\Sun\Java\lib\ext
sun.boot.class.path = c:\users\jlitw\.i4j_jres\1.8.0_152-tzdata2019c_64\lib\resources.jar;c:\users\jlitw\.i4j_jres\1.8.0_152-tzdata2019c_64\lib\rt.jar;c:\users\jlitw\.i4j_jres\1.8.0_152-tzdata2019c_64\lib\sunrsasign.jar;c:\users\jlitw\.i4j_jres\1.8.0_152-tzdata2019c_64\lib\jsse.jar;c:\users\jlitw\.i4j_jres\1.8.0_152-tzdata2019c_64\lib\jce.jar;c:\users\jlitw\.i4j_jres\1.8.0_152-tzdata2019c_64\lib\charsets.jar;c:\users\jlitw\.i4j_jres\1.8.0_152-tzdata2019c_64\lib\jfr.jar;c:\users\jlitw\.i4j_jres\1.8.0_152-tzdata2019c_64\classes
java.vendor = Oracle Corporation
file.separator = \
java.vendor.url.bug = http://bugreport.sun.com/bugreport/
sun.io.unicode.encoding = UnicodeLittle
sun.cpu.endian = little
sun.desktop = windows
sun.locale.formatasdefault = true
sun.cpu.isalist = amd64
------------------------------------------------------------
13:38:11:716 IBController: using default settings provider: ini file is C:\IBC\IBcontroller.ini
13:38:11:716 IBController: using default login manager: getting username and password from args
13:38:11:716 IBController: using default config dialog manager: constructor parameter isGateway=false
13:38:11:717 IBController: using default trading mode manager: constructor parameter args: tradingMode=live
13:38:11:717 IBController: using default config dialog manager
13:38:11:720 IBController: IBControllerServer is started.
13:38:11:790 IBController: Ensuring C:\Jts\jts.ini contains required minimal lines
13:38:11:790 IBController: Found section: [Logon]
13:38:11:790 IBController: Can't find setting: s3store=false
13:38:11:790 IBController: Found section: [Logon]
13:38:11:790 IBController: Found setting: s3store=true
13:38:11:790 IBController: Found section: [IBGateway]
13:38:11:790 IBController: Found setting: ApiOnly=true
13:38:11:790 IBController: Confirmed C:\Jts\jts.ini contains required minimal lines
13:38:11:790 IBController: TWS settings directory is C:\Jts
13:38:12:058 IBController: IBControllerServer listening on addresses: 127.0.0.1,0:0:0:0:0:0:0:1,fe80:0:0:0:1123:c782:75a8:a017%net5,192.168.1.157; port: 7462
13:38:15:237 IBController: detected frame entitled: Login; event=Activated
13:38:15:242 IBController: detected frame entitled: Login; event=Opened
13:38:15:246 IBController: detected frame entitled: Login; event=Activated
13:41:00:869 IBController: detected frame entitled: Login; event=Activated
13:41:01:004 IBController: detected frame entitled: Login; event=Closing
13:41:01:023 IBController: detected frame entitled: Login; event=Closed
IBController finished

**Comment by rlktradewright** [comment]
Trouble is you're trying to run IBController, but IBController is DEAD, DEAD, DEAD!!! IBController doesn't work at all with any current version of TWS or Gateway, because it's an unmaintained project.

This repository is for IBC, which superseded IBController several years ago. See the 'History' section on the main page of this repository.

So you'll have to start again. Nuke your IBController installation: there is nothing in it that is of any value whatsoever.

Read the User Guide for IBC, because it's not the same as IBController. Then set up everything again using the latest download for IBC.

User Guide is here: https://github.com/IbcAlpha/IBC/blob/master/userguide.md, and also in the zip.

**Comment by jlitz** [comment]
Yes i know that.   I am running the new IBC version have removed the IBC controller version created an IBC directory in which i installed the 3.10   Have copied .ini to IBC folder in documents .  I guess I am 

still getting the tws window to open but user and password not being inserted   I must be something simple I can not figure out  been working on it a few hours.

bat:  set TWS_MAJOR_VRSN=1010
set IBC_INI=c:\IBC\
set TRADING_MODE=
set IBC_PATH=c:\IBC
set TWS_PATH=c:\Jts
set LOG_PATH=c:\IBC\Logs
set TWSUSERID=xxxxxx
set TWSPASSWORD=xxxxx
set JAVA_PATH=
set HIDE=


================================================================================

Starting IBController version 3.4.0 on Sun 10/03/2021 at 15:32:32.55

Operating system:  Microsoft Windows 10 Home  64-bit          10.0.19043  


Arguments:

TWS version = 1010
Entry point = ibcontroller.IBController
/TwsPath = C:\Jts
/IbcPath = C:\IBC
/IbcIni = C:\IBC\IBcontroller.ini
/Mode = live
/JavaPath = 
/User = ***
/PW = ***
/FIXUser =
/FIXPW =

=================================

Generating the classpath
Classpath=C:\Jts\1010\jars\jts4launch-1010.jar;C:\Jts\1010\jars\jxbrowser-7.17.jar;C:\Jts\1010\jars\jxbrowser-swing-7.17.jar;C:\Jts\1010\jars\jxbrowser-win64-7.17.jar;C:\Jts\1010\jars\locales.jar;C:\Jts\1010\jars\log4j-api-2.12.0.jar;C:\Jts\1010\jars\log4j-core-2.12.0.jar;C:\Jts\1010\jars\total-2020.jar;C:\Jts\1010\jars\twslaunch-1010.jar;C:\Jts\1010\jars\twslaunch-install4j-1.10.jar;C:\IBC\IBController.jar

Generating the JAVA VM options
Java VM Options= -Xmx768m -XX:+UseG1GC -XX:MaxGCPauseMillis=200 -XX:ParallelGCThreads=20 -XX:ConcGCThreads=5 -XX:InitiatingHeapOccupancyPercent=70 -Dinstaller.uuid=4304bcb2-10c2-44eb-b7a6-a74cb5fcdd7c -DvmOptionsPath=C:\Jts\1010\tws.vmoptions -Dsun.awt.nopixfmt=true -Dsun.java2d.noddraw=true -Dswing.boldMetal=false -Dsun.locale.formatasdefault=true

Determining the location of java.exe 
Location of java.exe=c:\users\jlitw\.i4j_jres\1.8.0_152-tzdata2019c_64\bin

Starting IBController with this command:
"c:\users\jlitw\.i4j_jres\1.8.0_152-tzdata2019c_64\bin\java.exe" -cp  "C:\Jts\1010\jars\jts4launch-1010.jar;C:\Jts\1010\jars\jxbrowser-7.17.jar;C:\Jts\1010\jars\jxbrowser-swing-7.17.jar;C:\Jts\1010\jars\jxbrowser-win64-7.17.jar;C:\Jts\1010\jars\locales.jar;C:\Jts\1010\jars\log4j-api-2.12.0.jar;C:\Jts\1010\jars\log4j-core-2.12.0.jar;C:\Jts\1010\jars\total-2020.jar;C:\Jts\1010\jars\twslaunch-1010.jar;C:\Jts\1010\jars\twslaunch-install4j-1.10.jar;C:\IBC\IBController.jar"  -Xmx768m -XX:+UseG1GC -XX:MaxGCPauseMillis=200 -XX:ParallelGCThreads=20 -XX:ConcGCThreads=5 -XX:InitiatingHeapOccupancyPercent=70 -Dinstaller.uuid=4304bcb2-10c2-44eb-b7a6-a74cb5fcdd7c -DvmOptionsPath=C:\Jts\1010\tws.vmoptions -Dsun.awt.nopixfmt=true -Dsun.java2d.noddraw=true -Dswing.boldMetal=false -Dsun.locale.formatasdefault=true ibcontroller.IBController "C:\IBC\IBcontroller.ini" "***" "***" live

15:32:32:740 IBController: Properties file C:\Users\jlitw\Documents\IBController\IBController.ini not found
System Properties
------------------------------------------------------------
swing.boldMetal = false
java.runtime.name = Java(TM) SE Runtime Environment
sun.boot.library.path = c:\users\jlitw\.i4j_jres\1.8.0_152-tzdata2019c_64\bin
java.vm.version = 25.152-b16
sun.awt.nopixfmt = true
vmOptionsPath = C:\Jts\1010\tws.vmoptions
java.vm.vendor = Oracle Corporation
java.vendor.url = http://java.oracle.com/
path.separator = ;
java.vm.name = Java HotSpot(TM) 64-Bit Server VM
file.encoding.pkg = sun.io
user.country = US
user.script = 
sun.java.launcher = SUN_STANDARD
sun.os.patch.level = 
java.vm.specification.name = Java Virtual Machine Specification
user.dir = C:\Jts
java.runtime.version = 1.8.0_152-b16
java.awt.graphicsenv = sun.awt.Win32GraphicsEnvironment
java.endorsed.dirs = c:\users\jlitw\.i4j_jres\1.8.0_152-tzdata2019c_64\lib\endorsed
os.arch = amd64
java.io.tmpdir = C:\WINDOWS\TEMP\
line.separator = 

java.vm.specification.vendor = Oracle Corporation
user.variant = 
os.name = Windows 10
sun.java2d.noddraw = true
sun.jnu.encoding = Cp1252
java.library.path = c:\users\jlitw\.i4j_jres\1.8.0_152-tzdata2019c_64\bin;C:\WINDOWS\Sun\Java\bin;C:\WINDOWS\system32;C:\WINDOWS;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Users\jlitw\AppData\Roaming\ActiveState\bin;C:\windows\system32;C:\windows;C:\windows\System32\Wbem;C:\windows\System32\WindowsPowerShell\v1.0\;C:\windows\System32\OpenSSH\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files (x86)\Common Files\Intel\Shared Libraries\redist\intel64_win\compiler;C:\Users\jlitw\AppData\Local\Microsoft\WindowsApps;;.
java.specification.name = Java Platform API Specification
java.class.version = 52.0
sun.management.compiler = HotSpot 64-Bit Tiered Compilers
os.version = 10.0
user.home = C:\Users\jlitw
user.timezone = America/New_York
installer.uuid = 4304bcb2-10c2-44eb-b7a6-a74cb5fcdd7c
java.awt.printerjob = sun.awt.windows.WPrinterJob
file.encoding = Cp1252
java.specification.version = 1.8
java.class.path = C:\Jts\1010\jars\jts4launch-1010.jar;C:\Jts\1010\jars\jxbrowser-7.17.jar;C:\Jts\1010\jars\jxbrowser-swing-7.17.jar;C:\Jts\1010\jars\jxbrowser-win64-7.17.jar;C:\Jts\1010\jars\locales.jar;C:\Jts\1010\jars\log4j-api-2.12.0.jar;C:\Jts\1010\jars\log4j-core-2.12.0.jar;C:\Jts\1010\jars\total-2020.jar;C:\Jts\1010\jars\twslaunch-1010.jar;C:\Jts\1010\jars\twslaunch-install4j-1.10.jar;C:\IBC\IBController.jar
user.name = jlitw
java.vm.specification.version = 1.8
sun.java.command = ibcontroller.IBController C:\IBC\IBcontroller.ini beach294 stpete77 live
java.home = c:\users\jlitw\.i4j_jres\1.8.0_152-tzdata2019c_64
sun.arch.data.model = 64
user.language = en
java.specification.vendor = Oracle Corporation
awt.toolkit = sun.awt.windows.WToolkit
java.vm.info = mixed mode
java.version = 1.8.0_152
java.ext.dirs = c:\users\jlitw\.i4j_jres\1.8.0_152-tzdata2019c_64\lib\ext;C:\WINDOWS\Sun\Java\lib\ext
sun.boot.class.path = c:\users\jlitw\.i4j_jres\1.8.0_152-tzdata2019c_64\lib\resources.jar;c:\users\jlitw\.i4j_jres\1.8.0_152-tzdata2019c_64\lib\rt.jar;c:\users\jlitw\.i4j_jres\1.8.0_152-tzdata2019c_64\lib\sunrsasign.jar;c:\users\jlitw\.i4j_jres\1.8.0_152-tzdata2019c_64\lib\jsse.jar;c:\users\jlitw\.i4j_jres\1.8.0_152-tzdata2019c_64\lib\jce.jar;c:\users\jlitw\.i4j_jres\1.8.0_152-tzdata2019c_64\lib\charsets.jar;c:\users\jlitw\.i4j_jres\1.8.0_152-tzdata2019c_64\lib\jfr.jar;c:\users\jlitw\.i4j_jres\1.8.0_152-tzdata2019c_64\classes
java.vendor = Oracle Corporation
file.separator = \
java.vendor.url.bug = http://bugreport.sun.com/bugreport/
sun.io.unicode.encoding = UnicodeLittle
sun.cpu.endian = little
sun.desktop = windows
sun.locale.formatasdefault = true
sun.cpu.isalist = amd64
------------------------------------------------------------
15:32:32:747 IBController: using default settings provider: ini file is C:\IBC\IBcontroller.ini
15:32:32:747 IBController: using default login manager: getting username and password from args
15:32:32:747 IBController: using default config dialog manager: constructor parameter isGateway=false
15:32:32:747 IBController: using default trading mode manager: constructor parameter args: tradingMode=live
15:32:32:748 IBController: using default config dialog manager
15:32:32:750 IBController: IBControllerServer is started.
15:32:32:818 IBController: Ensuring C:\Jts\jts.ini contains required minimal lines
15:32:32:818 IBController: Found section: [Logon]
15:32:32:818 IBController: Can't find setting: s3store=false
15:32:32:818 IBController: Found section: [Logon]
15:32:32:819 IBController: Found setting: s3store=true
15:32:32:819 IBController: Found section: [IBGateway]
15:32:32:819 IBController: Found setting: ApiOnly=true
15:32:32:819 IBController: Confirmed C:\Jts\jts.ini contains required minimal lines
15:32:32:819 IBController: TWS settings directory is C:\Jts
15:32:33:113 IBController: IBControllerServer listening on addresses: 127.0.0.1,0:0:0:0:0:0:0:1,fe80:0:0:0:1123:c782:75a8:a017%net5,192.168.1.157; port: 7462
15:32:36:345 IBController: detected frame entitled: Login; event=Activated
15:32:36:351 IBController: detected frame entitled: Login; event=Opened
15:32:36:359 IBController: detected frame entitled: Login; event=Activated

**Comment by jlitz** [comment]
Yes I realize that  I have the new version of IBC installed and have read the guide.  Been working on it but no success yet.  TWS  sign on panel opens but no log on info inputed.   I will eventually figure it out.  ID user and PW in .ini are recognized.  Obviously I got something wrong

set TWS_MAJOR_VRSN=1010
set IBC_INI=C:\IBC
set TRADING_MODE=live
set IBC_PATH=c:\ibc
set TWS_PATH=C:\Jts
set LOG_PATH=C:\ibc\Logs
set TWSUSERID=
set TWSPASSWORD=
set JAVA_PATH=
set HIDE=

17:15:46:198 IBController: using default settings provider: ini file is C:\IBC\IBcontroller.ini
17:15:46:198 IBController: using default login manager: getting username and password from args
17:15:46:198 IBController: using default config dialog manager: constructor parameter isGateway=false
17:15:46:198 IBController: using default trading mode manager: constructor parameter args: tradingMode=live
17:15:46:199 IBController: using default config dialog manager
17:15:46:201 IBController: IBControllerServer is started.
17:15:46:262 IBController: Ensuring c:\jts\jts.ini contains required minimal lines
17:15:46:263 IBController: Found section: [Logon]
17:15:46:263 IBController: Can't find setting: s3store=false
17:15:46:263 IBController: Found section: [Logon]
17:15:46:263 IBController: Found setting: s3store=true
17:15:46:263 IBController: Found section: [IBGateway]
17:15:46:263 IBController: Found setting: ApiOnly=true
17:15:46:263 IBController: Confirmed c:\jts\jts.ini contains required minimal lines
17:15:46:263 IBController: TWS settings directory is c:\jts
17:15:46:544 IBController: IBControllerServer listening on addresses: 127.0.0.1,0:0:0:0:0:0:0:1,fe80:0:0:0:1123:c782:75a8:a017%net5,192.168.1.157; port: 7462
17:15:49:578 IBController: detected frame entitled: Login; event=Activated
17:15:49:584 IBController: detected frame entitled: Login; event=Opened
17:15:49:591 IBController: detected frame entitled: Login; event=Activated
^C

**Comment by rlktradewright** [comment]
No, you haven't done that properly. Sorry to be rude, but can't you read? Look at the log file: it says 'IBController' everywhere! You are still running the IBController code. IBC never ever logs anything that starts with 'IBController'.

Not only that, but if you had read the User Guide you would know that the config for IBC is in config.ini, not in IBController.ini. Don't try to use an old IBController.ini file as a config.ini file: the settings are not the same!

And `set IBC_INI=C:\IBC` is completely wrong: there is no `IBC_INI` variable in StartTWS.bat. Here's what the variable settings in StartTWS.bat look like on my computer:

```
set TWS_MAJOR_VRSN=1010
set CONFIG=%HOMEDRIVE%%HOMEPATH%\Documents\IBC\config.ini
set TRADING_MODE=
set TWOFA_TIMEOUT_ACTION=exit
set IBC_PATH=%SYSTEMDRIVE%\IBC
set TWS_PATH=%SYSTEMDRIVE%\Jts
set TWS_SETTINGS_PATH=
set LOG_PATH=%IBC_PATH%\Logs
set TWSUSERID=
set TWSPASSWORD=
set JAVA_PATH=
set HIDE=
```

Just to be clear, the zip file that you should be downloading is for IBC version 3.10.0 from this page:

https://github.com/IbcAlpha/IBC/releases/tag/3.10.0

So please, once again delete your C:\IBC folder because it is obviously completely screwed: I don't know what you've done, I'm not a mind reader. Then download the zip file above, and start again, following the instructions in the User Guide. FOLLOW THEM EXACTLY AS THEY ARE! If you follow them, you cannot fail to succeed. 

In fact, the instructions in the User Guide distil down to the following to get you started:

* download the zip file from the link above
  
* extract the contents to C:\IBC

* move the C:\IBC\config.ini file to %HOMEDRIVE%%HOMEPATH%\Documents\IBC\config.ini so that only you have access to it

* in C:\StartTWS.bat:
  
  set TWS_MAJOR_VRSN=981

* in %HOMEDRIVE%%HOMEPATH%\Documents\IBC\config.ini:
  - put your IB user ID in the `IbLoginId` setting
  - put your IB password in the `IbPassword` setting
  - change the `TradingMode` setting to `live` (though I'd recommend you leave it set to `paper` until you've got it working 
   properly)

That's it!

PLEASE NOTE: if you want to include extract(s) from the IBC logfile in your comments here, the best thing to do is to attach the whole file. Don't quote it inline (it makes the thread really difficult to follow and navigate round). And when I say 'the whole file'. I mean the whole thing, not just bits of it.

**Comment by jlitz** [comment]
Ok got it. works.  Thank you.  Very nice program.  I don't know how the references to ibcontroller got in there  guess i did not delete it thoroughly.
