### ISSUE TITLE
IBC failed to activate TWS gateway when screen is locked

### ISSUE THREAD

**Issue by bobprc** [IbcAlpha/IBC#146]
I'm running IBC in OSX. When the screen is unlocked, it works smoothly without problem: the TWS gateway can be displayed and username/password can be submitted and login request can be made. The log is shown in the ibc_success.log. 

However, when the screen is locked (not sleep), the IBC will be stuck at login process where the gatetway login screen is displayed but not activated, with no username and password filled in. After sometime (60 seconds) the login will be terminated and another retry will be performed.  The failure log can be found in the ibc_failure.log. 

[ibc_failure.log](https://github.com/IbcAlpha/IBC/files/7357844/ibc_failure.log)
[ibc_success.log](https://github.com/IbcAlpha/IBC/files/7357845/ibc_success.log)

**Comment by rlktradewright** [comment]
I suspect that what's happening here is that the Gateway is displaying the pop-up that asks you whether to restart using SSL or exit altogether.

IBC version 3.8.7 that you are using does not handle this dialog. You need to upgrade to at least v3.9.0 or, better, the latest 3.10.0.

Just download the zip from https://github.com/IbcAlpha/IBC/releases/tag/3.10.0, and extract the `IBC.jar` and `version` files into your IBC folder.

For future reference, when you attach a log file please attach the whole thing, not just the part(s) you think might be relevant.

**Comment by bobprc** [comment]
> I suspect that what's happening here is that the Gateway is displaying the pop-up that asks you whether to restart using SSL or exit altogether.
> 
> IBC version 3.8.7 that you are using does not handle this dialog. You need to upgrade to at least v3.9.0 or, better, the latest 3.10.0.
> 
> Just download the zip from https://github.com/IbcAlpha/IBC/releases/tag/3.10.0, and extract the `IBC.jar` and `version` files into your IBC folder.
> 
> For future reference, when you attach a log file please attach the whole thing, not just the part(s) you think might be relevant.

Thanks for your comments! 

I think the version I'm using is already 3.10.0, as you can see in the log.
