### ISSUE TITLE
Incoming forced 981.3 update

### ISSUE THREAD

**Issue by TengXu94** [IbcAlpha/IBC#152]
Dear All,
Does anybody knows if this tool will work with the TWS v981.3?
<img width="992" alt="Screenshot 2021-11-29 at 08 02 57" src="https://user-images.githubusercontent.com/11192941/144764823-01e6b285-09c0-4a6d-b61f-72f59f5a9b3f.png">

Thank you all for your feedback,
Best
Andrea

**Comment by rlktradewright** [comment]
Yes, it works fine with all current versions of TWS and Gateway.

Make sure you read and understand the comments at the start of the User Guide regarding the fact that you can no longer keep TWS 974 or later running for more than one day with IBC. You'll need to make some decisions about how you deal with this.

**Comment by TengXu94** [comment]
Thank you for your prompt reply @rlktradewright .

Do I understand correctly that from TWS 974 onwards, IBC works fine as long as the session duration is kept lower than 24h?

**Comment by rlktradewright** [comment]
Yes. Read the User Guide and the comments for the `IbAutoClosedown` setting in config.ini.

**Comment by TengXu94** [comment]
Thank you for your help! @rlktradewright

**Comment by d3an** [comment]
I have IBC v3.11.1 working with the latest gateway version, v981.3e.

**Comment by rickygu** [comment]
I'm on IBC 3.8.2 and TWS 978 with multiple accounts running. To update TWS and IBC, do I just replace the IBC.jar and version files with new IBC 3.11.1. Install latest TWS (currently 10.11.2f). Then update TWS_MAJOR_VRSN in twsstart.sh? Anything else I need to change? is there a version update guide?

**Comment by rlktradewright** [comment]
My recommendation would be to rename your existing IBC folder (eg Ibc.old), then install the new version from scratch to ensure you get all the changed files. Then make sure you carry forward any customizations to start scripts and config.ini, including TWS_MAJOR _VRSN.

There is no version update guide as such. I often give explicit instructions in the release descriptions.

**Comment by d3an** [comment]
Not sure if it helps, but [here's](https://github.com/d3an/ib-gateway-docker-v981) a reference to my setup (IB Gateway v981.3e, IBC 3.11.1).

**Comment by TengXu94** [comment]
Thank you all guys, forgot to close the issue.
I am currently running IBC Controller with TWS v10.11 :)
