### ISSUE TITLE
Gateway blocked by "Settings will not be downloaded from the server because the feature has been temporarily disabled" dialog

### ISSUE THREAD

**Issue by tredondo** [IbcAlpha/IBC#153]
I'm running 3.11.1 with 972 and ran into this dialog:

![image](https://user-images.githubusercontent.com/10043369/145091505-69cb8c5a-952c-4479-9a0f-5f84a2b23bc8.png)

[ibc-3.11.1_GATEWAY-972_Thursday - Settings will not be downloaded.txt](https://github.com/IbcAlpha/IBC/files/7671001/ibc-3.11.1_GATEWAY-972_Thursday.-.Settings.will.not.be.downloaded.txt)

**Comment by rlktradewright** [comment]
I don't want to have to modify IBC to handle this if it's only a temporary problem.

Can you not just turn off the 'store settings on server' setting for the moment?

**Comment by tredondo** [comment]
The problem is I've never changed that setting, and when running Gateway manually, I don't see it:

![image](https://user-images.githubusercontent.com/10043369/145095440-4be3228e-7279-47db-ae7f-a838c1123a29.png)

If I log into that dialog manually, Gateway starts, but `gatewaystart.sh` runs into that dialog. If I click "OK" in that dialog, Gateway remains stuck at `Requesting startup parameters...`.

**Comment by rlktradewright** [comment]
Ah, I see your problem. I assumed you must have set it in `config.ini`, but now I look closely at the log file I can see you didn't.

And what's really weird is that the Gateway doesn't offer this option at all. So I'm afraid this is just IB getting it all wrong...

Well, there's certainly nothing I can do about it immediately, and it sounds from what you say that anything IBC did would not help - all it could do would be to click the OK button.

Just have to hope they fix it soon. In the meantime, use TWS instead?

I'm out of circulation tomorrow and Thursday, so I hope you can get back into action somehow.

**Comment by tredondo** [comment]
Is it possible that IBC causes the display of that prompt? If I don't use IBC and just launch `gateway`, the prompt is never displayed and Gateway functions as before.

**Comment by tredondo** [comment]
I tried using TWS 972.1x, but it gets stuck at "Reading settings file...". The checkbox to use/store settings on server was unchecked.

![image](https://user-images.githubusercontent.com/10043369/145319104-02300fc9-7d30-4c3d-a764-1b0b676d29e7.png)

**Comment by rlktradewright** [comment]
Apologies, I forgot to respond to this.

I suspect that this might have the same cause as issue #151, so please try installing the latest IBC version 3.12.0-beta.2 and see if that improves things.

**Comment by ceeyee** [comment]
IBC version 3.12.0-beta.2 works now on 976 without the error.

**Comment by rlktradewright** [comment]
@ceeyee thank you, that's good to know.

**Comment by tredondo** [comment]
It worked! IBC version 3.12.0-beta.2 launched Gateway! TWS is still [stuck](https://github.com/IbcAlpha/IBC/issues/153#issuecomment-989417196) at "Reading settings file...", but I don't use TWS so I'm good.
