### ISSUE TITLE
"Settings will not be downloaded from the server because the feature has been temporarily disabled"

### ISSUE THREAD

**Issue by ceeyee** [IbcAlpha/IBC#154]
Today this error keeps popping up and it has prevented IBC 3.8.2 to function on Gateway 976.2e.  It happens during the "Requesting startup parameters" stage.

Please note that Gateway is able to start without this error when it's launched manually (not through IBC).

Can you please fix that? I really need it to work.
Thank you very much.

![image](https://user-images.githubusercontent.com/17518929/145625530-fb8f32f4-7c92-44ad-a1b9-2cc85cde61c7.png)

**Comment by rlktradewright** [comment]
Please don't create duplicate issues! This is obviously the same thing as Issue #153.

So I'm going to close this one. If you need to respond further, do it on #153.
