### ISSUE TITLE
Why IBGateway not able to finish initialization?

### ISSUE THREAD

**Issue by oemGitHub** [IbcAlpha/IBC#16]
Recently, IBGateway cannot finish initialization during login, and I would like to know on how to solve this issue.

IBGateway version 963.3m
IBC version 3.6.0
Furthermore, I have also tried and download the IBGateway latest version 7xx, and still do not have luck on initialization during login process, but I can login TWS without any problem, which confirm no problem with my account.

Does anyone have any suggestions on how to solve it?
Thanks in advance for any suggestions

**Comment by rlktradewright** [comment]
You haven't given any useful information. You haven't even explained what you mean.

So please tell us what you mean by 'not able to finish initialization', and attach your IBC log file.

**Comment by oemGitHub** [comment]
Please see attached file and image, on image, would it be normal the text is grey color at the left bottom corner?
Do you have any suggestions?
Thank you very much for any suggestions (^v^)


[IB_Log.txt](https://github.com/IbcAlpha/IBC/files/2161284/IB_Log.txt)

![ib](https://user-images.githubusercontent.com/22294237/42247697-7fa8d8e6-7f54-11e8-923e-8ad082d5ae00.png)

**Comment by rlktradewright** [comment]
There seems to be a problem with the Gateway. IBC appears to be working correctly.

The error messages in the log file that say `[Fatal Error] :1:1: Content is not allowed in prolog.` are from the Gateway.

I notice that you have a 64-bit operating system but you are using a 32-bit Gateway. I suggest you uninstall your current gateway, and download and install the 64-bit gateway: the current stable version is 963.3o dated 20180515.

**Comment by oemGitHub** [comment]
I use Excel DDE to connect IBGateway, so 32-bit Gateway is a must, which is suggested by IB support.
[Fatal Error] :1:1: Content is not allowed in prolog.
Do you have any suggestions on what error message it is?
Thank you very much for any suggestions (^v^)

**Comment by rlktradewright** [comment]
If I knew what the error message means, I would have told you before.

 

You need to contact IB support to ask them what this error means.

 

I cannot help you.

**Comment by oemGitHub** [comment]
I re-install IBGateway, it works fine now, but I would like to know on why the display text color are different as shown on below images.

Do you have any suggestions?
Thank you very much for any suggestions (^v^)
