### ISSUE TITLE
Is there a way to automate the 2FA?  

### ISSUE THREAD

**Issue by paulbanyny** [IbcAlpha/IBC#161]
Is there a way to automatically populate the 2FA / second factor authentication field? Having to access my phone for every log in attempt kind of eliminates the benefit of automating everything in the first place. 
Am I missing something?

**Comment by rlktradewright** [comment]
I assume that you're already using the IBKR Mobile app to complete the 2FA sequence, and that it's this operation that you're objecting to?

And the answer is NO. This is an irreducible minimum. Actually it seems pretty darn good to me: it could hardly be easier.
 
In 'the old days' you had to fiddle around with plastic or electronic cards, and manually type a code into the window on your computer: which meant you had to actually be at the computer. But now all you have to do is acknowledge a prompt on your phone. You could be in a hotel in Hong Kong or on the beach in the Bahamas while your computer running TWS is thousands of miles away: you don't even need to get out of bed!

If the whole 2FA were entirely automated, it would completely defeat the point of 2FA. Nothing would guarantee that the computer was running TWS with your personal involvement. So why would IBKR then be willing to take the risk of providing guarantees against fraudulent use?

**Comment by spidLL** [comment]
If you have the Pro account, you can create another user and that one won't need 2fa. It takes few days for the new user to be fully operative though (for example to share the data subscriptions).
