### ISSUE TITLE
Removing/Automating DDE Socket Bridge Connection Prompt?

### ISSUE THREAD

**Issue by fettekatz** [IbcAlpha/IBC#164]
Following up on my post from last week, the latest TWS 1015 no longer allows you to use Legacy DDE and forces you to use DDE Socket Bridge.

I got Socket Bridge working with x64 TWS 1015, API 1015, and IBC 3.13 Beta, which requires one to follow IB's [guide](https://interactivebrokers.github.io/tws-api/dde_intro.html) and install the standalone Java. It seems to be an improvement from my older x86 TWS versions using Legacy DDE - the requests are faster and TWS seems to have less display issues during non-market times such as today's market holiday.

However running runDdeSocketBridge.bat (which is required to connect the API) prompts this popup that has to be accepted:
![Capture](https://user-images.githubusercontent.com/103332534/163623869-e74b7baa-0d58-44ce-ad5a-81dc16ede426.JPG)

As far as I can tell, there's no editing of the .bat that gets rid of the prompt. Restarting TWS disconnects DDE Socket Bridge and forces you to restart the runDdeSocketBridge.bat, showing that prompt again. I use Windows Task Scheduler to open and exit TWS daily, and as far as I know the newest TWS versions still require daily restarts.

Is there a way to automate removing that prompt? If this is outside IBC's limitations, I've also submitted and IB ticket and I'll share their answer with everyone here.

**Comment by rlktradewright** [comment]
See the AcceptIncomingConnectionAction setting in config.ini.

 

 

From: fettekatz ***@***.***> 
Sent: 15 April 2022 20:32
To: IbcAlpha/IBC ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [IbcAlpha/IBC] DDE Socket Bridge Prompt Auto-Accept? (Issue #164)

 

Following up on my post from last week, I got IB's DDE Socket bridge working with TWS 1015 x64, API 1015, and IBC 3.13 Beta, which requires one to follow IB's guide <https://interactivebrokers.github.io/tws-api/dde_intro.html>  and install the standalone Java. It's great, the requests are faster and TWS seems to have less display issues during non-market times such as today's market holiday.

However running runDdeSocketBridge.bat prompts this popup that has to be accepted:
 <https://user-images.githubusercontent.com/103332534/163623869-e74b7baa-0d58-44ce-ad5a-81dc16ede426.JPG> 

As far as I can tell, there's no editing of the .bat that gets rid of the prompt. Restarting TWS disconnects DDE Socket Bridge and forces you to restart the runDdeSocketBridge.bat, showing that prompt again. I use Windows Task Scheduler to open and exit TWS daily, and as far as I know the newest TWS versions still require daily restarts.

Is there a way to automate removing that prompt? Thanks
