### ISSUE TITLE
invalid twsInfo error 2022 version

### ISSUE THREAD

**Issue by twanko** [IbcAlpha/IBC#166]
Since a few days i get this "invalid twsInfo" error when i try to start any version of ibgateway standalone using ibc.

I'm using the " 3.12.0-beta.2 " release. 

When i start ibgateway without ibc it works flawlessly.

It first started on a desktop vps which was using a papertrade account. But yesterday it also started appearing on a desktop vps with a live account. Both linux.

Today i even get it on my development machine, which is a windows machine.

I tried everything including everything in the previous "invalid twsInfo error" thread.

Did somebody else get this error since a few days?

**Comment by FrankyHo** [comment]
> Since a few days i get this "invalid twsInfo" error when i try to start any version of ibgateway standalone using ibc.
> 
> I'm using the " 3.12.0-beta.2 " release.
> 
> When i start ibgateway without ibc it works flawlessly.
> 
> It first started on a desktop vps which was using a papertrade account. But yesterday it also started appearing on a desktop vps with a live account. Both linux.
> 
> Today i even get it on my development machine, which is a windows machine.
> 
> I tried everything including everything in the previous "invalid twsInfo error" thread.
> 
> Did somebody else get this error since a few days?
![screenshot_submit](https://user-images.githubusercontent.com/35860407/165738592-88c27e66-cc4b-4ec9-8abc-a31de139e30f.jpg)

I got similar problem suddenly,  I try remove the IbLoginId and IbPassword in config.ini. problem still same

**Comment by rlktradewright** [comment]
Can you people not read?!!!

What's the point of this post that just says 'me too' and adds no useful information?

Attach your IBC logfile! Is that too much to ask?

**Comment by FrankyHo** [comment]
[ibc-3.8.5_GATEWAY-978_Thursday.txt](https://github.com/IbcAlpha/IBC/files/8582200/ibc-3.8.5_GATEWAY-978_Thursday.txt)

sorry, miss log file

**Comment by FrankyHo** [comment]
hi @rlktradewright 

attach early log before show "invaild twsinfo" and quit, hope this could help.

[ibc-3.8.5_GATEWAY-978_Wednesday.txt](https://github.com/IbcAlpha/IBC/files/8582518/ibc-3.8.5_GATEWAY-978_Wednesday.txt)

**Comment by rlktradewright** [comment]
Can you all please make sure you're using the latest version of IBC. This is currently 3.12.0.

In particular the subscripts `StartIBC.bat` (Windows) and `ibcstart.sh`(Linux/macOS) changed back in December when this issue was first raised. So if you're not using them, then of course it's not working!

@FrankyHo using IBC 3.8.5 and Gateway 978 is just asking for trouble. I can't provide support for these old versions.

**Comment by FrankyHo** [comment]
hi @rlktradewright 

after upgrade to 3.12.0, problem solve, thank you.

**Comment by jbeyer05** [comment]
First time posting on this thread, but I experienced this same issue with the Gateway with IBC 3.11.0, and can confirm that an upgrade to 3.12.0 fixed the issue for me.

Thanks for all your work Richard!

**Comment by twanko** [comment]
Cheers, i can confirm that adding the extra vm options works. I'm using my own startup process with the 3.12.0 code, but overlooked the changes made to the startup scripts.
It's a bit strange that it wasn't needed in the last 4 months and suddenly became needed, but i don't complain.
One handy feature of github is the compare feature:
https://github.com/IbcAlpha/IBC/compare/3.11.1...3.12.0-beta.2
Makes missing things less frequent.
