### ISSUE TITLE
IBC 3.8.2 unable to shut down IB Gateway via Telnet on 1015

### ISSUE THREAD

**Issue by PhilGuerra** [IbcAlpha/IBC#168]
I was forced to upgrade from 978 to 1015.  Now, IBC (version 3.8.2) isn't able to fill out the username and password for IB Gateway 1015.  This issue has previously been reported (issue #165).

However, previously I was able to sent a telnet command and shut down the IB Gateway instance.  Now with 1015 and 3.8.2, I receive this error message, and the instance isn't able to be shut down no matter which button I choose in the new dialog box at the bottom:

![Screenshot from 2022-05-10 23-19-02](https://user-images.githubusercontent.com/39604666/167770132-20301869-6672-426c-87d6-82299250b14b.png)

**Comment by rlktradewright** [comment]
I don't understand what you mean. If you're running 1015, you can't be running IBC 3.8.2. Please clarify.

**Comment by rlktradewright** [comment]
Closed due to lack of further input.

**Comment by PhilGuerra** [comment]
I'm sorry I didn't respond until now.  As you mentioned, I shouldn't be on
3.8.2 with 1015.  I updated IBC to the latest version, and no issues - just
excellence.  Thank you for

As a bonus, 1015 is ultra stable.  Previously my code would sometimes
experience an error shortly after transmitting orders on IBG, or it would
sometimes re-request to login with SSL.  Now...it's 100% reliable
automation finallu.  Thanks to IBC too of course.
