### ISSUE TITLE
Unable to launch IBGateway v981

### ISSUE THREAD

**Issue by joshuapack** [IbcAlpha/IBC#169]
So, we have been using IBGateway 972 and recently it is no longer supported.

I tried upgrading to 981 and 1015 with no avail.

I have tried upgrading IBC all the way up to 3.13.0-beta.3. In 972, it still launches correctly and logs in, but the box comes up(saying i need to upgrade) and doesn't allow it to run the api. In 981, IBC never launches the program, and manually launching it does not auto log in.

Attached is log:
[ibc-3.13.0-beta.3_GATEWAY-981_Wednesday.txt](https://github.com/IbcAlpha/IBC/files/8673626/ibc-3.13.0-beta.3_GATEWAY-981_Wednesday.txt)

It just keeps trying and never succeeds. would there be a permission issue? On windows it runs fine, it's just linux where it isn't running. It is a headless Linux on Ubuntu, but I have VNC running on a Virtual Framebuffer so I can do it manually. any other info I should provide? I tried working on this for 8 hours, and I couldn't get it to start IBGateway. unless running 972. any other versions don't work. (running manually works fine, example running `DISPLAY=:0 ./ibgateway` will launch it correctly)

**Comment by rlktradewright** [comment]
I see from the logfile that you are trying to run it with OpenJDK. In my experience, TWS/Gateway have never worked properly with OpenJDK, so it might be worth removing that setting so that it uses the JVM included in the install.

I can't see anything else that might cause problems.

**Comment by joshuapack** [comment]
Thanks, I will try that. I'll respond back if it works or not.

**Comment by joshuapack** [comment]
Dang that was it!

8 hours down the drain! lol

Really appreciate it!
