### ISSUE TITLE
Why the display text color are different for IBGateway?

### ISSUE THREAD

**Issue by oemGitHub** [IbcAlpha/IBC#17]
I re-install IBGateway, it works fine now, but I would like to know on why the display text color are different as shown on below images.

N.B. I cannot upload images

Do you have any suggestions?
Thank you very much for any suggestions (^v^)

Linked image:
http://i1093.photobucket.com/albums/i438/junk000/IBG_zpscaaylq88.png

**Comment by rlktradewright** [comment]
The Gateway is Interactive Brokers' software. 

IBC is NOT Interactive Brokers' software. 

So I have absolutely nothing to do with what Gateway looks like. You must ask IB this question.
