### ISSUE TITLE
Stable IBGateway 10.12 for Linux changed the installed path

### ISSUE THREAD

**Issue by stock888777** [IbcAlpha/IBC#174]
Today, the stable IBGateway 10.12 for Linux is released.
Its installed path is changed.

https://github.com/IbcAlpha/IBC/blob/3.13.0/resources/gatewaystart.sh#L26 should be
```
TWS_PATH=~
```

https://github.com/IbcAlpha/IBC/blob/3.13.0/resources/scripts/ibcstart.sh#L231 should be
```
	if [ "$tws_path" = "" ]; then tws_path=~ ;fi
```

https://github.com/IbcAlpha/IBC/blob/3.13.0/resources/scripts/ibcstart.sh#L249 should be
```
	gateway_vmoptions="${tws_path}/ibgateway/ibgateway.vmoptions"
	gateway_jars="${tws_path}/ibgateway/jars"
	gateway_install4j="${tws_path}/ibgateway/.install4j"
```

But these changes cannot coexist with IBGateway 9.81.
And many files are created in the home directory.

**Comment by rlktradewright** [comment]
I don't know where you got the stable Gateway 10.12 from: I can only find the 'latest' 10.16 version. I'd be grateful if you could tell me where to find it.

So I installed Gateway10.16 on a virgin Ubuntu 20.04 system, and it installed in exactly the same place as it always has, ie:

`~/Jts/ibgateway/1016`

I installed and configured IBC and it ran perfectly.

I see no reason to believe that 10.12 would install differently. I suggest you uninstall everything and start again.

**Comment by stock888777** [comment]
I downloaded it from here.

- stable https://www.interactivebrokers.com/en/index.php?f=16457
- latest https://www.interactivebrokers.com/en/trading/ibgateway-latest.php

The stable is 10.12.2l and the latest is 10.16.1f .

I installed using this script.

```
cd ~
wget --quiet https://download2.interactivebrokers.com/installers/ibgateway/stable-standalone/ibgateway-stable-standalone-linux-x64.sh
chmod +x ibgateway-stable-standalone-linux-x64.sh
./ibgateway-stable-standalone-linux-x64.sh -q
```

**Comment by rlktradewright** [comment]
_[Thanks for that link to the Gateway download. Odd though, the only way I can find Gateway via the website navigation (ie not via search) is using the Login button and then selecting 'Download IB Gateway', and that only offers the 'latest' version. What am I missing?]_

Ah, well done there!

I had just spent quite a while investigating this and coming to exactly the same conclusions as you, except that I failed to discover the -dir argument. I was just about to submit my comment when yours appeared.

Just for the record, the solution I came up with was to add an extra command after the install:

```
cd ~
mv ibgateway Jts/ibgateway/1012
```

This gets everything in the right place for IBC, but unfortunately it requires knowledge of the Gateway version number being installed, which is not ideal (mind you so does your better solution).

I find it somewhat annoying that the default install location is different between the GUI mode and the unattended mode.

By all means close the issue if you're happy with things now.

**Comment by stock888777** [comment]
> I find it somewhat annoying that the default install location is different between the GUI mode and the unattended mode.

I hope Interactive Brokers will fix this.

> By all means close the issue if you're happy with things now.

I will close.
