### ISSUE TITLE
close prompt window after log in

### ISSUE THREAD

**Issue by skandari-uk** [IbcAlpha/IBC#175]
Hi,
First thanks for providing such excellent software.
It would be great to have the command prompt window automatically close after log in is successfully done or at least if the user closes the window, the TWS/IB does not close afterwards.
Thank you,

**Comment by rlktradewright** [comment]
Doesn't the `HIDE` setting in the start scripts meet your needs?

If you use this, the command prompt window will be minimised to the taskbar (it's not possible to remove it altogether). If you subsequently restore it, and then close it, it will still kill TWS/Gateway. I don't think it would be possible to prevent closing that window from closing the program.

There is also a setting in config.ini to minimise TWS/Gateway, so you can hide the whole thing pretty effectively.

**Comment by rlktradewright** [comment]
@skandari-uk  Any further input on this?

**Comment by skandari-uk** [comment]
Thanks for the reply.
Having the prompt window clutters my desktop.

**Comment by rlktradewright** [comment]
Ok but are you satisfied now?

If so, please close the issue.

**Comment by skandari-uk** [comment]
Thanks for the help any way.
