### ISSUE TITLE
Java Library of TWS Actions

### ISSUE THREAD

**Issue by jamesrdf** [IbcAlpha/IBC#181]
Great Project!

I want to help make IBC useful as a Java library. I'd like to create a PR that separates the settings from the actions. Would such a PR be welcome? Any suggestions, guidance or feedback on how I best to approach this?

I like the functionality the Java code provides, but I don't want to use the scripts or ini config files. How can we separate the incredibly useful java code to control TWS, without binding it to the ini settings?

To test this out I pulled some code out of IbcTws and into another class[1] that uses parameters instead of Settings.settings() and makes the actions public so it can be used as a Java library. I've been using this code for two years and seems stable, so I'd like to find a way to merge this concept back into IBC.

[1] https://github.com/jamesrdf/ib-tws-shell/blob/701110588a208595be847588fc91ef90dd837433/src/ibcalpha/ibc/TWSManager.java

**Comment by rlktradewright** [comment]
You don't need to do anything to use IBC as a library. It can already be used in that way.

It already includes a simple dependency injection mechanism that enables you to provide your own replacements for the Settings, LoginManager, MainWindowManager and TradingModeManager modules.

What's more there is a sample project showing how to do this here: https://github.com/IbcAlpha/IBC/tree/master/samples/IbcLoader

This sample project hasn't been updated for a couple of years, so it will need to be edited, in particular to change the hard-coded user id and password, which are currently for the now-defunct Demo system that IB used to provide. Also it uses a Windows script to start it, which enables it to run under the same Java runtime that is installed with TWS and Gateway, but that is merely a convenience for running the sample: in a real scenario you would presumably be invoking IBC from your own Java code, using your own scripts if appropriate.

You mention making the actions public: I don't have time to check out your code just now so I'm not quite sure what you have in mind here, but I'm not averse to making some functions public that currently aren't, if there is really a valid use case for it.

**Comment by rlktradewright** [comment]
I thought I'd better try to see if this sample still works, and I've discovered that things have moved on somewhat since I developed it and it's no longer functional.

So I need to bring it up-to-date. What's holding it up at the moment is the MyLoginManager class which is missing some interactions: all the 2FA stuff in IBC has been introduced since then, and I'll probably have to enhance the AbstractLogin Manager to include default implementation of this stuff.  

I'll let you know when it's done, but it probably won't be today.

**Comment by jamesrdf** [comment]
The public methods in the class linked above include the list below. It would be nice if these actions were available in the IBC when used as a library.

- boolean isOpen()
- void start(Class<?> mainClass, String ibDir)
- void stop(boolean isGateway)
- int enableAPI(Integer portNumber, Boolean readOnly)
- void saveSettings()
- void reconnectData()
- void reconnectAccount()

**Comment by rlktradewright** [comment]
Sorry for the delay in responding to this. I haven't had time to give it any real thought yet because of the work on auto-restart for v3.15.

I'll try to get to it soon.

**Comment by jamesrdf** [comment]
I've also been working on that using -javaagent in tws.vmoptions. Are you using a similar approach?

**Comment by jamesrdf** [comment]
With the auto-restart and required second factor authentication, I don't have as much need for IBC anymore.

**Comment by yezhengli-Mr9** [comment]
> With the auto-restart and required second factor authentication, I don't have as much need for IBC anymore.

Dear @catch-point, any simpler alternative to IBC with the auto-restart and second-factor authentication.
Best and thanks,

**Comment by catch-point** [comment]
I use https://github.com/catch-point/ib-tws-node (obviously), but the features don't overlap with IBC. It just provides TWS API access for node (using Java API w/o a separate Java process). I manually log to TWS desktop every week and let it auto-restart daily.
