### ISSUE TITLE
IBC Login with 2FA

### ISSUE THREAD

**Issue by wangxiaoweishy** [IbcAlpha/IBC#184]
can IBC support that ibgateway could restart by the restart time configuration in the setting dialog, and does not need authenticate 2FA every day (only once a week)?

**Comment by rlktradewright** [comment]
I'm just working on this at the moment.

This has become possible because of a change in IB's implementation of the autorestart mechanism (so it won't work with TWS versions before 1018).

I'm hoping to release this enhancement very soon.

**Comment by wangxiaoweishy** [comment]
> I'm just working on this at the moment.
> 
> This has become possible because of a change in IB's implementation of the autorestart mechanism (so it won't work with TWS versions before 1018).
> 
> I'm hoping to release this enhancement very soon.

That a great message for us!
