### ISSUE TITLE
Improve logging in the various shell scripts

### ISSUE THREAD

**Issue by walterdolce** [IbcAlpha/IBC#189]
I noticed the various startup/mgmt scripts produce very few log entries. As a first-time user of IBC, I had to go through quite a few hoops to figure out what I and the tool were doing [wrong].

I customise all the params I can get my hands to (location of config.ini, version of IBKR/IBC, location of logs, etc), and this probably contributed to the confusion in adopting the tool.

I think a lot more logging info could be spit out by the various sh/bat scripts, and I am happy to do the work. So with this what I'm really saying is: folks/maintainers happy for me to go and do that?

Let me know. Thx

**Comment by rlktradewright** [comment]
Sorry I'm baffled by what you're saying.

Can you give me some examples of things that you feel ought to be logged?

I fail to understand why, as a first-time user, you'd want to 'customise all the params I can get my hands on'. The whole thing has been honed over the years to make it just about as easy as possible to install, if you use the default settings and follow the instructions. 

My advice is to use the defaults as far as possible, get some experience with it, and when you're familiar with how it works then start thinking about things you want to change, if there is really any reason to do so.

If you feel that the User Guide or the extensive comments in the start scripts and the ini files are lacking in some way, please suggest ways in which they can be improved. I'm always willing to improve clarity, add missing information, correct inconsistencies etc.

**Comment by walterdolce** [comment]
I followed the instructions to get a taste of it. But then I needed to do it as per my needs, I'll send a PR soon with more `echo`s and `print`s.

**Comment by walterdolce** [comment]
Actually, ignore the above. I can see there's plenty of debugging info already that is generated when IBC starts up.

I noticed the following however, which confused me a little.

1. When the LOG_PATH var is set to something in the scripts, IBC would log to that file. No issues here.
2. When the LOG_PATH var is _not_ set, then IBC logs stuff on the same terminal window
3. When the LOG_PATH var is set _but it's empty_, then IBG defaults to logging stuff on `/dev/null` ? Why the choice of making all logging info disappear in /dev/null? Why is this not /dev/stdout instead?

BTW - setting LOG_PATH to /dev/stdout should not result in:
```
+ Diagnostic information is logged in:
+
+ /dev/stdout/ibc-3.15.2_GATEWAY-10.20_Saturday.txt
```

**Comment by walterdolce** [comment]
Here's what I would do in relation to the above, please do feel free to ignore.

1. In all startup scripts, give users the ability to set control variables manually (as done now) as well as injecting them via environment variables, like so:
```
# either pick TWS_MAJOR_VRSN from user-provided env var, or use 10.20 as default
TWS_MAJOR_VRSN=${TWS_MAJOR_VRSN:-10.20}
```
2. For the LOG_PATH variable specifically, apply the same logic as per 1) above, and either default to `/dev/stdout` or keep the current default
3. Remove the current condition that leads to logging to `/dev/null`, but default to `/dev/stdout`. Also, treat any `/dev/*` as special paths (so that if people do specify /dev/* then the script won't append a finename to it as described above)

Hope the above makes sense
