### ISSUE TITLE
bindaddr is taken from a wrong config option (Linux, not sure about other OS')

### ISSUE THREAD

**Issue by papadp** [IbcAlpha/IBC#19]
`CommandServer.java` states `final String bindaddr = Settings.settings().getString("IbBindAddress", "");`
while `config.ini` comes with `BindAddress=`.

 I see the user guide states 
> the IbBindAddress setting has been renamed to BindAddress

So I'm guessing the code should state that, see [PR#18](https://github.com/IbcAlpha/IBC/pull/18)

**Comment by rlktradewright** [comment]
PR  #18 has been merged.
