### ISSUE TITLE
2FA Login without a user action

### ISSUE THREAD

**Issue by DanielLichtenecker** [IbcAlpha/IBC#194]
Hi,

what is the best way to avoid a user action due to the recent mandatory 2nd factor enrollment? Currently I'm using IBRK Mobile for the 2FA, but it needs an active user action which is not convenient. Is there a way to proceed without a user action?

**Comment by rlktradewright** [comment]
If you set up IBC correctly it could hardly be more convenient. You get the prompt on your Android or IOS mobile device, you acknowledge it, and that's it. If you miss the prompt for any reason, you'll get another chance after a few minutes: and this will continue until you do it.

If you're hoping you could somehow get logged in without doing anything at all, dream on!... That wouldn't be 2FA.

**Comment by yarimiz** [comment]
A recommendation I got from IBKR support is to set the gateway setting to auto restart instead of auto logoff, this will require a user interaction for authentication only once a week.

Read more here: https://ibkrguides.com/tws/usersguidebook/configuretws/auto_restart_info.htm

**Comment by melkayam92** [comment]
Hey @rlktradewright, how exactly can i log once a week with IBC? what config should i use?

**Comment by rlktradewright** [comment]
Read the User Guide, and the comments in `config.ini`.
