### ISSUE TITLE
Starting Automatically with Systemd

### ISSUE THREAD

**Issue by jaredvacanti** [IbcAlpha/IBC#2]
I'm struggling to use IBC with `systemd` on Ubuntu 16.04 LTS. I have seen some posts detailing how to start IBController with systemd and would like to implement the same for IBC - I'd be happy to detail a guide on how to set it up correctly once I get it working. Now I am using a detached screen session in production, which works fine but if anything happens to the system itself it will not correct itself without manual intervention. I could do a "periodic test" with `cron`, but I prefer the robustness of `systemd` alongside other architecture.

Here is my unit file: 

```
[Unit]
Description=Job that runs the IBController for paper account
Requires=xvfb.service
After=xvfb.service

[Service]
Environment="DISPLAY=:0"
ExecStart=/opt/ibc/gatewaystart.sh
Restart=always

[Install]
WantedBy=multi-user.target
```
Note: xvfb is working fine on restart. Now when I restart my machine I set the display variable and `gatewaystart.sh` does everything perfectly (manually).

Richard - I had noticed a thread in the groups.io page about waiting for a banner to load on a new version that you had released (could this be related?). Just an idea.

The error I'm getting from `journalctl` is too many reload attempts from systemd:

```
-- Logs begin at Tue 2018-03-20 19:16:19 UTC, end at Tue 2018-03-20 19:17:44 UTC. --
Mar 20 19:16:24 ip-172-31-40-221 systemd[1]: ibcontroller-paper.service: About to execute: /opt/ibc/gatewaysta
Mar 20 19:16:24 ip-172-31-40-221 systemd[1]: ibcontroller-paper.service: Forked /opt/ibc/gatewaystart.sh as 11
Mar 20 19:16:24 ip-172-31-40-221 systemd[1]: ibcontroller-paper.service: Changed dead -> running
Mar 20 19:16:24 ip-172-31-40-221 systemd[1]: ibcontroller-paper.service: Job ibcontroller-paper.service/start 
Mar 20 19:16:24 ip-172-31-40-221 systemd[1]: Started Job that runs the IBController for paper account.
Mar 20 19:16:24 ip-172-31-40-221 systemd[1126]: ibcontroller-paper.service: Executing: /opt/ibc/gatewaystart.s
Mar 20 19:16:24 ip-172-31-40-221 systemd[1]: ibcontroller-paper.service: Service hold-off time over, schedulin
Mar 20 19:16:24 ip-172-31-40-221 systemd[1]: Stopped Job that runs the IBController for paper account.
Mar 20 19:16:24 ip-172-31-40-221 systemd[1]: Started Job that runs the IBController for paper account.
Mar 20 19:16:24 ip-172-31-40-221 systemd[1]: ibcontroller-paper.service: Service hold-off time over, schedulin
Mar 20 19:16:24 ip-172-31-40-221 systemd[1]: Stopped Job that runs the IBController for paper account.
Mar 20 19:16:24 ip-172-31-40-221 systemd[1]: Started Job that runs the IBController for paper account.
Mar 20 19:16:24 ip-172-31-40-221 systemd[1266]: ibcontroller-paper.service: Executing: /opt/ibc/gatewaystart.s
Mar 20 19:16:25 ip-172-31-40-221 systemd[1]: ibcontroller-paper.service: Service hold-off time over, schedulin
Mar 20 19:16:25 ip-172-31-40-221 systemd[1]: Stopped Job that runs the IBController for paper account.
Mar 20 19:16:25 ip-172-31-40-221 systemd[1]: Started Job that runs the IBController for paper account.
Mar 20 19:16:25 ip-172-31-40-221 systemd[1287]: ibcontroller-paper.service: Executing: /opt/ibc/gatewaystart.s
Mar 20 19:16:25 ip-172-31-40-221 systemd[1]: ibcontroller-paper.service: Service hold-off time over, schedulin
Mar 20 19:16:25 ip-172-31-40-221 systemd[1]: Stopped Job that runs the IBController for paper account.
Mar 20 19:16:25 ip-172-31-40-221 systemd[1]: Started Job that runs the IBController for paper account.
Mar 20 19:16:25 ip-172-31-40-221 systemd[1302]: ibcontroller-paper.service: Executing: /opt/ibc/gatewaystart.s
Mar 20 19:16:25 ip-172-31-40-221 systemd[1]: ibcontroller-paper.service: Service hold-off time over, schedulin
Mar 20 19:16:25 ip-172-31-40-221 systemd[1]: Stopped Job that runs the IBController for paper account.
Mar 20 19:16:25 ip-172-31-40-221 systemd[1]: ibcontroller-paper.service: Start request repeated too quickly.
Mar 20 19:16:25 ip-172-31-40-221 systemd[1]: Failed to start Job that runs the IBController for paper account.
```

Are there some points in the bash script I could add some verbose logging (printing) to see what's going on? 

I'll keep investigating and report back with any findings. If you'd like me to migrate to groups.io I can do that - but I thought others with similar issues may look here first. My apologies if this is the incorrect place to add the issue.

**Comment by jaredvacanti** [comment]
There were two problems: the `gatewaystart.sh` scripts runs as a background process - as noted by the trailing `&` at the end of the execution. With `systemd` this requires a `Type=forking` in the `[Service]` declaration, otherwise on exit systemd receives a successful exit code and cleans up everything associated with the process... and attempts a restart with the same problem.

Also, systemd runs as root by default, so all of the paths in `gatewaystart.sh` and `config.ini` need to be adjusted to absolute paths, or you need to include extra parameters in the unit file to run as a specific user in a specific directory. They appear to be relative paths by default (intentionally, not knowing someones particular user). This two fixes will allow systemd to run IBC automatically on restart and to attempt to restart on any failure. Here is the full unit file: 

```
[Unit]
Description=Job that runs the IBController for paper account
Requires=xvfb.service
After=xvfb.service

[Service]
Type=forking
Environment="DISPLAY=:0"
ExecStart=/opt/ibc/gatewaystart.sh
Restart=always

[Install]
WantedBy=multi-user.target
```

This is assuming that the official installation procedures were followed to have files in `/opt/ibc/`.

**Comment by rlktradewright** [comment]
Thanks @jaredvacanti that sounds like very useful information. My knowledge of `systemd` is non-existent, so this will give me a useful leg up to explore it a bit.
