### ISSUE TITLE
Stop.bat doesn't seem to be working

### ISSUE THREAD

**Issue by npowell88** [IbcAlpha/IBC#20]
IBC is very handy -- thank you for making it!

I made sure the telnet client is enabled in the windows and features. However, when I run the Stop.bat, it fails to stop the IB gateway process which is running as well as the window which is running IBC. Any ideas of what I can do to debug the issue? Thank you!

**Comment by rlktradewright** [comment]
Make sure the setting `CommandServerPort` in config.ini has a value., and that the same value is set in the Stop.bat file.

If it's already set the same in both places, then attach the IBC logfile to your reply.

**Comment by npowell88** [comment]
That was the issue; the CommandServerPort was commented out. Thanks!
