### ISSUE TITLE
SessionManager

### ISSUE THREAD

**Issue by jazefirst** [IbcAlpha/IBC#201]
Hi
first thanks for the great work.

The SessionManager.java is new in 3.16.0. Could you make the method _static void Initialise(boolean isGateway)_ public? I have my own startup class (which uses a different LoginManager, and calls after the initialization _ibcalpha.ibc.IbcTws.load()_). Before 3.16.0  the _DefaultMainWindowManager_ handled the isGateway parameter. Now I need to set it via _SessionManager.Initialise(isGateway)_ but I can't since it's not public.

Thanks
/Markus

**Comment by rlktradewright** [comment]
Thanks for pointing out this flaw. I'll get a new release out tomorrow.

**Comment by rlktradewright** [comment]
@jazefirst 

I've uploaded a new `IBC.jar` file for v3.16.1 to the repository along with the code changes. Haven't had time to do a release for it yet, so just download the `IBC.jar` and the `version` file.
