### ISSUE TITLE
Group does not exist

### ISSUE THREAD

**Issue by meteorpublish** [IbcAlpha/IBC#21]
https://github.com/IbcAlpha/IBC/releases/tag/3.6.0 links to [the IBController User Group](https://groups.io/g/ibcontroller), which does not exist.

**Comment by rlktradewright** [comment]
Thanks. It was true at the time...

Fixed.

**Comment by meteorpublish** [comment]
Thanks for the quick fix. https://groups.io/g/ibcalpha exists, should that be linked instead?

**Comment by rlktradewright** [comment]
I think the amendment I made is sufficient. Linking the user group was not the purpose of the original comment, so I see no reason to link it now.
