### ISSUE TITLE
paper account login handle

### ISSUE THREAD

**Issue by qijiepan** [IbcAlpha/IBC#215]
![image](https://github.com/IbcAlpha/IBC/assets/10191969/c0cf9923-cf7b-4409-a177-24b8161a4869)
if we use paper account login with 3.16.2 
it has the pop up and can ibc handle that?

Many thanks!

**Comment by steven-varga** [comment]
I am having similar problem with IBGateway 1025 , how has this been resolved?

**Comment by qijiepan** [comment]
yes. config the parameter `AcceptNonBrokerageAccountWarning`
