### ISSUE TITLE
Suppress Message Deprecated DDE Clients

### ISSUE THREAD

**Issue by Chris181920** [IbcAlpha/IBC#223]
Hallo, 
with the TWS Offline Version 1023, is there a way to suppress the message "Your Trader Workstation is running 32bit Java ...." and "Click OK to proceed and enable Deprecated DDE Clients" which arises always when starting TWS.

Maybe I missed some previous discussion about it, thanks for any hint and help!
Regards Chris

![Clipboard01](https://github.com/IbcAlpha/IBC/assets/139373228/ea66f220-492a-4abf-b2c4-5576604cc54a)

**Comment by rlktradewright** [comment]
No there isn't a way. Of course IBC could be enhanced to detect this and click OK, but I seen absolutely no reason to do this.

The error message tells you exactly what you should do. Is there any reason why you can't just do that?
