### ISSUE TITLE
cat not  start IBC, IBC closing after TWS/Gateway failed to display login dialog.

### ISSUE THREAD

**Issue by passionofvc** [IbcAlpha/IBC#225]
After I update IB gateway from version 1016 to  version 1024, IBC can not start,
it show below finished message, so I downgrade to version 1016, the IBC started success.
But Interactive Brokers LLC send me a mail and tell me must to update to latest version [1024](https://download2.interactivebrokers.com/installers/ibgateway/latest-standalone/ibgateway-latest-standalone-linux-x64.sh).

TWS version = 1024
IBC: Version: 3.8.3

```
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
2023-07-28 17:54:01:941 IBC: IBC closing after TWS/Gateway failed to display login dialog
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Gateway finished
```

The below version run also for one year and do not have any problem. 
TWS version = 1016
IBC: Version: 3.8.3

Do I need to update newest IBC version?

**Comment by rlktradewright** [comment]
Yes you need to update to the latest version. 

You are miles behind!.

**Comment by passionofvc** [comment]
I attach this logs
[1024-ibc-start-error.log](https://github.com/IbcAlpha/IBC/files/12193137/1024-ibc-start-error.log)

**Comment by passionofvc** [comment]
@rlktradewright 
Thanks your anwser.
so why TWS version = 1016 and IBC: Version: 3.8.3 worked? I can not understand this.
Is there anything about how to know what min limit TWS version does IBC need to run?

**Comment by rlktradewright** [comment]
The notes for Release 3.17.0 tell you why: IB changed the format of the Gateway login dialog.

When IB change something like this, IBC has to be updated to cope with the change, hence a new release is needed. Every time a new release is issued, you get informed about it if you're watching the repository. Also I notify the members of the IBC User Group (https://groups.io/g/ibcalpha).

It's your responsibility to keep yourself informed about changes to the software, and I provide full details to enable you to do so, and to decide whether you need to upgrade.

**Comment by passionofvc** [comment]
@rlktradewright 
Thank you for your prompt reply.
