### ISSUE TITLE
Precautionary Settings of Global Configuration/Presets, limiting orders where value is 100,000

### ISSUE THREAD

**Issue by SidGoy** [IbcAlpha/IBC#227]
I just switched from TWS 10.21 and IBC 3.17.0 - everything worked perfectly.

to:

TWS 10.24 and IBC 3.17.0 -- this had so many issues from TWS side that I switched to:

Side note - This has left a fractional quantity(0.59) in a Forex pair which is not close-able. If there is a solution to this please let me know.

TWS 10.19 - stable and IBC 3.17.0

I tried to place an order:

Order(orderId=329, clientId=417, permId=1523601942, action='SELL', totalQuantity=5.0, orderType='STP LMT', lmtPrice=15491, auxPrice=15499, tif='GTC', ocaType=3, displaySize=2147483647, outsideRth=True, rule80A='0', trailStopPrice=15450.0, openClose='', volatilityType=0, deltaNeutralOrderType='None', referencePriceType=0, account='U1215xxxxx', clearingIntent='IB', adjustedOrderType='None', cashQty=0.0, dontUseAutoPriceForHedge=True)

I get the following error:

>Error 451, reqId 329: The following order "ID:329" value estimate of 154,990 USD exceeds  the Total Value Limit of 100,000 USD. Restriction is specified in Precautionary Settings of Global Configuration/Presets.

> Canceled order: Trade(contract=Future(conId=568549458, symbol='MNQ', lastTradeDateOrContractMonth='20230915', right='?', multiplier='2', exchange='CME', currency='USD', localSymbol='MNQU3', tradingClass='MNQ'), order=Order(orderId=329, clientId=417, permId=1523601942, action='SELL', totalQuantity=5.0, orderType='STP LMT', lmtPrice=15491, auxPrice=15499, tif='GTC', ocaType=3, displaySize=2147483647, outsideRth=True, rule80A='0', trailStopPrice=15450.0, openClose='', volatilityType=0, deltaNeutralOrderType='None', referencePriceType=0, account='U1215xxx', clearingIntent='IB', adjustedOrderType='None', cashQty=0.0, dontUseAutoPriceForHedge=True), orderStatus=OrderStatus(orderId=329, status='Cancelled', filled=0.0, remaining=5.0, avgFillPrice=0.0, permId=1523601942, parentId=0, lastFillPrice=0.0, clientId=417, whyHeld='', mktCapPrice=0.0), fills=[], log=[TradeLogEntry(time=datetime.datetime(2023, 9, 1, 10, 30, 0, 690201, tzinfo=datetime.timezone.utc), status='Submitted', message='', errorCode=0), TradeLogEntry(time=datetime.datetime(2023, 9, 1, 10, 31, 28, 931810, tzinfo=datetime.timezone.utc), status='Submitted', message='Modify', errorCode=0), TradeLogEntry(time=datetime.datetime(2023, 9, 1, 10, 32, 26, 824138, tzinfo=datetime.timezone.utc), status='Cancelled', message='Error 451, reqId 329: The following order "ID:329" value estimate of 154,990 USD exceeds  the Total Value Limit of 100,000 USD. Restriction is specified in Precautionary Settings of Global Configuration/Presets.', errorCode=451)], advancedError='')

I didn't find this setting in the config.ini file. I went into the >Presets>Stocks and see a bunch of enabled fields which I assumed would be overridden by the API.

**Comment by rlktradewright** [comment]
These settings are only overriden in the API if you set 'Bypass Order Precautions for API Orders' in the Precautions section of  the TWS/Gateway API settings.

Also check out the latest release 3.18.0 which enables you to set these via config.ini: https://github.com/IbcAlpha/IBC/releases/tag/3.18.0

**Comment by SidGoy** [comment]
@rlktradewright 

Thanks for the quick reply and the awesome work.

It used to work flawlessly. But I noticed the issue after downgrading to 10.19 related to the settings.

The only way I got it to work was by using the new 3.18.0 version of IBC with 10.19 TWS/Gateway and specifying the override settings to yes. Plus deleting the presets of stocks, futures, etc(I never set these).

**Comment by rlktradewright** [comment]
These presets are the default settings for TWS (and Gateway) as installed, so that's why you've never set them yourself. They are provided for your protection, to help prevent accidentally placing large orders that bust your account (either manually of via the API). It's worthwhile considering carefully before removing or overrinding the precautions for your live account.

If you haven't seen the 'order ... value estimate ... exceeds the Total Value Limit' message before, it's presumably because you haven't placed an order that large before. They've been there in TWS/Gateway for very many versions.

By the way, TWS 10.24 and IBC 3.18.0 work perfectly well together.
