### ISSUE TITLE
What are valid `CommandServerPort` commands?

### ISSUE THREAD

**Issue by gnzsnz** [IbcAlpha/IBC#237]
I'm wondering how to use the `CommandServerPort` functionality. is there a list of valid commands?

I could not find anything on the user guide, nor on config.ini. I found some examples on [ibcalpha group](https://groups.io/g/ibcalpha) but not a full list of commands.

Any input would be appreciated. Thanks in advance.

**Comment by rlktradewright** [comment]
Rather than write it up here, I'll add a section to the User Guide. This has been needed for a long time, so it's about time I did it.

If I haven't said here that's its done after a few days, feel free to remind me!

**Comment by ownrepo1s** [comment]
Reminder :D

**Comment by rlktradewright** [comment]
Thanks. Soon...

**Comment by gnzsnz** [comment]
kind reminder

**Comment by rlktradewright** [comment]
Yesterday I added a section on the IBC Command Server to the User Guide. It's near the end of the document.

I also added a set of simple scripts for both Windows and Unix.

These updates will be included in the zips for the next release. I might do a point release if that doesn't happen soon.

In the meantime users can dowload the updated User Guide and the scripts from here. Note that these scripts are standalone: IBC itself doesn't need to be installed on the computer where they are used.  Use the links below to navigate to the required file, then click the 'Download raw file' button at the top right, and save to any convenient folder (if IBC is installed, the IBC folder is a sensible place alongside the existing scripts).

[User Guide](https://github.com/IbcAlpha/IBC/blob/master/resources/userguide.pdf)

**Windows scripts:** You can run these from any Windows computer - it doesn't have to be the one running IBC. The target computer can be either WIndows or Unix.

[EnableAPI.bat](https://github.com/IbcAlpha/IBC/blob/master/resources/EnableAPI.bat)

[ReconnectAccount.bat](https://github.com/IbcAlpha/IBC/blob/master/resources/ReconnectAccount.bat)

[ReconnectData.bat](https://github.com/IbcAlpha/IBC/blob/master/resources/ReconnectData.bat)

[Restart.bat](https://github.com/IbcAlpha/IBC/blob/master/resources/Restart.bat)

[SendCommand.bat](https://github.com/IbcAlpha/IBC/blob/master/resources/SendCommand.bat)

[Stop.bat](https://github.com/IbcAlpha/IBC/blob/master/resources/Stop.bat)

Download this one to a subfolder called `scripts`:

[SendIBCCommand.vbs](https://github.com/IbcAlpha/IBC/blob/master/resources/scripts/SendIBCCommand.vbs)

**Unix scripts:** You can run these from any Unix computer - it doesn't have to be the one running IBC. The target computer can be either Unix or Windows.

[commandsend.sh](https://github.com/IbcAlpha/IBC/blob/master/resources/commandsend.sh)

[enableapi.sh](https://github.com/IbcAlpha/IBC/blob/master/resources/enableapi.sh)

[reconnectaccount.sh](https://github.com/IbcAlpha/IBC/blob/master/resources/reconnectaccount.sh)

[reconnectdata.sh](https://github.com/IbcAlpha/IBC/blob/master/resources/reconnectdata.sh)

[restart.sh](https://github.com/IbcAlpha/IBC/blob/master/resources/restart.sh)

[stop.sh](https://github.com/IbcAlpha/IBC/blob/master/resources/stop.sh)

**Comment by gnzsnz** [comment]
this is fantastic, thanks a lot
