### ISSUE TITLE
ErrorLevel=1004

### ISSUE THREAD

**Issue by Timikk1** [IbcAlpha/IBC#240]
Hi I have a issue with starting IBC. I have set up everything correctly but it still do not work, it sends me error message please help me. Thank you very much for your time. I almost forgot I have stable version of TWS 10.19

![Screenshot 2023-12-05 162948](https://github.com/IbcAlpha/IBC/assets/153001094/8a34541c-a1f2-4a2c-9037-f1411175f528)
![Screenshot 2023-12-05 163009](https://github.com/IbcAlpha/IBC/assets/153001094/80ee0938-60cc-4c7b-b224-fc0d989fe86d)
![Screenshot 2023-12-05 163304](https://github.com/IbcAlpha/IBC/assets/153001094/2c744bec-d177-4826-a646-15345ee691a3)

**Comment by rlktradewright** [comment]
No, you haven't set up everything correc.tly.

You have installed the auto-updating version of TWS, not the offline version. As the error message clearly says, IBC does not work with the auto-updating version.

You can find the download for the offline version on the same website page as the auto-updating version, just a bit further down.

**Comment by rlktradewright** [comment]
In that case, you must have changed the installer's default installation directory from `C:\Jts\1019` to `C:\Jts`. Don't do that - just install to the default.

`C:\Jts` is the default installation folder for TWS, and is what `TWS_PATH` variable in StartTWS.bat should be set to. There are subfolders for each version installed, the subfolder name being the version number (without the period).

So TWS 10.19 installs to `C:\Jts\1019`, and TWS 10.26 installs to `C:\Jts\1026`.

Please uninstall TWS, and reinstall in the detault folder.

**Comment by Timikk1** [comment]
Thank you for your response but now i have different problem it sends me error 1006 :Error: IBC configuration file: C:\Users\timot\Documents\IBC\config.ini  does not exist 

But i have everything set up like before = in my documents folder i have folder IBC and in it i have config.ini 

![Screenshot 2023-12-06 135358](https://github.com/IbcAlpha/IBC/assets/153001094/a918fcb2-e93d-4ced-9b79-df57dd0ed11b)
 Thank you for your respond and time.

**Comment by rlktradewright** [comment]
That error message means what it says. The file is not there! (Or perhaps TWS doesn't have read access to it - I'm not sure without looking through the code whether that would give a different error.)

Your screenshot is not helpful because it doesn't show th path and it doesn't show the file extension. 

If you still can't figure this out, please attach your IBC logfile to your reply (the whole thing please, and attach it, don't quote it). It contains a lot of very useful information that might help diagnose the problem.
