### ISSUE TITLE
IBC 3.18.0 failed to click "I understand and accept" on warning dialog "This is a paper account" on TWS 10.26.1h

### ISSUE THREAD

**Issue by akatsev** [IbcAlpha/IBC#241]
Hi,
This is the content of the log file when the warning dialog is active and nothing is happen:
[IBC-3.18.0_TWS-1026_TUESDAY - Copy.txt](https://github.com/IbcAlpha/IBC/files/13581757/IBC-3.18.0_TWS-1026_TUESDAY.-.Copy.txt)
An this is the content of the log after I clicked "I understand and accept" myself.
[IBC-3.18.0_TWS-1026_TUESDAY - Copy (2).txt](https://github.com/IbcAlpha/IBC/files/13581790/IBC-3.18.0_TWS-1026_TUESDAY.-.Copy.2.txt)
I tried this 3-4 times with the same results.
What is going here? Lack of compatibility of IBC and TWS versions? Are there any recommendation regarding the versions' choice?
Thank you in advance,
A. Katsev.

**Comment by rlktradewright** [comment]
In your config.ini, you need:

`AcceptNonBrokerageAccountWarning=yes`

**Comment by akatsev** [comment]
Yes, it works! Thanks a lot!

ср, 6 дек. 2023 г., 14:11 Richard L King ***@***.***>:
