### ISSUE TITLE
Unable to find Java installation on Docker container

### ISSUE THREAD

**Issue by muriatic** [IbcAlpha/IBC#254]
I'm trying to make a docker image using IBC. I have set up the structure of the container with two folders (/IBC, /Jts). In order to install IB Gateway I have to install it on my Linux VM, then copy the files over to my Docker folder (into /Jts). All is good in terms of creating the Docker image and running it up until running gatewaystart.sh, if I go into the logs, I see:
```
Determining the location of java executable
Could not find /usr/local/i4j_jres/Oda-jK0QgTEmVssfllLP/1.8.0_202/bin/java
Could not find /home/<userName>/Downloads/ibgateway-stable-standalone-linux-x64.sh.5208.dir/jre/bin/java
```

Is this a use case for specifying a Java folder? Any help is greatly appreciated !

**Comment by rlktradewright** [comment]
Why don't you look at an existing Docker where correct installation of Gateway is already been achieved? For example the one linked to in this issue post should be helpful:

https://github.com/IbcAlpha/IBC/issues/67#issuecomment-1792867294

There are quite a number of others if you take the time to look.

**Comment by muriatic** [comment]
@rlktradewright Thank you ! I was able to get it working.
