### ISSUE TITLE
tws version

### ISSUE THREAD

**Issue by LishanZhong** [IbcAlpha/IBC#26]
My tws version is 973. How can I use IBC? Or where I can get tws963?

**Comment by rlktradewright** [comment]
IBC works with any version of TWS later than 952.

You need to make sure you've set the version correctly in StartTWS.bat or StartGateway.bat.

This is explained in detail in the User Guide. If you haven't read that, you should do so before you do anything else!

**Comment by LishanZhong** [comment]
Now on the website , which one is offline version ?

**Comment by LishanZhong** [comment]
Can you send me a offline version TWS ？ OR can give me http link?

> IBC适用于晚于952的任何版本的TWS。
> 
> 您需要确保在StartTWS.bat或StartGateway.bat中正确设置版本。
> 
> “用户指南”中对此进行了详细说明。如果你还没有读过，你应该在做其他事情之前这样做！

Can you send me a offline version TWS ？ OR can give me http link?

**Comment by rlktradewright** [comment]
https://www.interactivebrokers.com/en/home.php > TECHNOLOGY > TWS Software

Please can you try a bit harder to help yourself? I don't have time to waste on trivial questions like this!

**Comment by idmgas** [comment]
Version 963 stopped working properly. Downloaded the stable 972, and changed the StartTWS.bat to specify 972 on TWS_MAJOR_VRSN line. Bat file says that 972 is not installed but it runs fine when launched manually. I noticed in my installed App & features list that the Traderworkstation no longer shows the version in the name (used to see TraderWorkstation 963). Is that part of the issue? What else can be done to run TWS 972 with IBC?

**Comment by rlktradewright** [comment]
If you have downloaded and installed THE OFFLINE VERSION of TWS, the only thing you need to do is change 963 to 972.

If the version number doesn't show up in your Apps & Features list, it's because you've installed the self-updating version, not the offline version.

**Comment by jperkins909** [comment]
not working with latest tws 974

**Comment by rlktradewright** [comment]
@jperkins909   

You are right: it doesn't work with 974. This is because IBKR have completely redesigned the login dialog, such that IBC no longer recognises it at all.

What's worse, a quick glance at the dialog's structure tells me that there is no way that IBC can actually fill in the username and password, or click the login button.

This could spell the end for IBC....

But let me think about it, and I'll see what I can do.
