### ISSUE TITLE
IBRK don't open anymore with IBC

### ISSUE THREAD

**Issue by premiumsB** [IbcAlpha/IBC#260]
Hello

I have a task scheduler starting IBC and when the task start, my IB authenticator open on my phone but when I put my code TWS won't open anymore on my PC. I asked one of my friend and same issue. 

Do you also have this problem now? Why my IBRK doesn't want to open anymore?

Thank you

**Comment by rlktradewright** [comment]
What code? IB sends an alert to your phone: all you have to do is acknowledge it. No need to enter any code. 

Perhaps you need to read IB's documentation on how 2FA works with IBKR Mobile.

**Comment by premiumsB** [comment]
Never mind it works now :)
