### ISSUE TITLE
How to force IB Gateway to start with usfuture market data farm on?

### ISSUE THREAD

**Issue by leebailey88** [IbcAlpha/IBC#261]
![Screenshot 2024-07-19 134136](https://github.com/user-attachments/assets/3e1038f2-109e-4e91-af1d-2bc77b8f1d59)

I'm trading futures. Sometimes my IB Gateway that's running in a Docker container starts with only the `usfarm` market data farm turned on, while other times it also includes `usfuture` and `usfuture.nj`. I've found that if it doesn't start with `usfuture` turned on, then I'm not able to get any market data for futures contracts at all until I restart the program and hopefully get lucky with `usfuture` being on next time.

Is there a way to force the `usfuture` on from a config or command line option? Maybe in jts.ini?

![Screenshot 2024-07-19 135038](https://github.com/user-attachments/assets/77059e4b-b1c6-400f-b863-79ec7d14b41d)

**Comment by rlktradewright** [comment]
IBC can only do things that a user can do via the Gateway (or TWS) UI.

Do you know a way to force Gateway to connect to a particular market data farm using the UI? 

No, neither do I.

So I guess that answers the question!

The fact is that market data farms are connected as required as a result of market data requests. In the case of Gateway, this can only be via API calls to reqMktData. If that doesn't do the trick, there's almost certainly something wrong with your API client's code. Make sure you're logging error messages. I can't believe that you could request market data for a futures contract and get no data without there being an error message that explains why.

**Comment by leebailey88** [comment]
Thanks for the quick reply! I see, I will keep digging on this particular issue.

In the meantime, I've noticed another problem:

![Screenshot 2024-07-22 112041](https://github.com/user-attachments/assets/6dfe2f13-311c-4275-b6af-3af09e0c142b)

When I use the `RECONNECTDATA` command, there's a confirmation modal that pops up. IBC doesn't seem to be automatically clicking the "OK" button to confirm that I want to reconnect data.

**Comment by rlktradewright** [comment]
You're right. The same is true of `RECONNECTACCOUNT`.

This seems to be new behaviour in some version of TWS/Gateway since 10.19, which doesn't produce this dialog. Can you please tell me which Gateway version you're using?

I'll fix it when I can find some time.

**Comment by rlktradewright** [comment]
This was fixed in release 3.20.0
