### ISSUE TITLE
Paper trading login and the "understand and accept" dialog

### ISSUE THREAD

**Issue by dmacd** [IbcAlpha/IBC#268]
Hi there - 

First of all, thank you for providing and supporting such a critical piece of the puzzle for IB users. This may be a dumb question but I found no ready answer after an hour of searching so here goes...

When I configure IBC to log in to my paper account, it works, but it gets stopped on the "This is not a real account blah blah blah click 'understand and accept'" to continue dialog. Once I click on it, the gateway functions and my clients can connect. Since this is part of a larger automation in my test environment, I cannot rely on being around to manually click that dialog. Is this a config setting I missed somewhere or is this a gap in IBC functionality?

(Not sure if relevant, but I'm using IBC inside of a container from https://github.com/extrange/ibkr-docker/)

Thank you.

**Comment by rlktradewright** [comment]
How about `AcceptNonBrokerageAccountWarning`?

**Comment by dmacd** [comment]
:man_facepalming: Thank you, somehow missed that one.
