### ISSUE TITLE
IBC stops the Gateway instead of autorestart in paper mode

### ISSUE THREAD

**Issue by akosmaroy** [IbcAlpha/IBC#275]
Hi,

I'm experiencing a phenomenon where IBC stops a Gateway instead of autorestart, see the log file attached.

I'm running two Gateways on the same X window environment with Xvfb. Can this be a contributing factor to this issue?

Ákos
[ibc-3.20.0_GATEWAY-1030_Tuesday.txt](https://github.com/user-attachments/files/17729134/ibc-3.20.0_GATEWAY-1030_Tuesday.txt)

**Comment by rlktradewright** [comment]
In your `config.ini` you have:
```
  AutoLogoffTime=10:10 PM
````
I suggest you read the notes in `config.ini` about `AutoLogoffTime` and `AutoRestartTime`. Hopefully you'll see that you want `AutoRestartTime`.
