### ISSUE TITLE
how to run a real and a paper IB Gateway session with IBC on the same machine?

### ISSUE THREAD

**Issue by akosmaroy** [IbcAlpha/IBC#276]
Hi,

I'm aiming to run a real and a paper IB Gateway on the same machine through IBC. How would this be done properly?

Currently what I have, but I still seem to be encountering issues:

- I have one Jts installation at /my/path/opt/Jts
- I have two copies of IBC at /my/path/opt/ibc-real and /my/path/opt/ibc-paper, with different command_server_port settings
- I have to X sessions using Xvfb, one at :100 for ibc-real and then :101 for ibc-paper
- I'm having a separate set of enviroment variables for each, for real:
```
export IB_TWS_HOST=127.0.0.1
export IB_TWS_PORT=4001
export IB_TWS_CLIENT_ID=100
export TWS_SETTINGS_PATH=/my/path/opt/ibc-real
export DISPLAY=:100
``` 
for paper:
```
export IB_TWS_HOST=127.0.0.1
export IB_TWS_PORT=4002
export IB_TWS_CLIENT_ID=101
export TWS_SETTINGS_PATH=/my/path/opt/ibc-real
export DISPLAY=:101
``` 

is this an appropriate way to run these, or should I also duplicate the Jts directory for example?

**Comment by rlktradewright** [comment]
Have you read the section in the User Guide on this topic? See here:

https://github.com/IbcAlpha/IBC/blob/master/userguide.md#multiple-ibc-instances

What are these environment variables that you mention? What is setting them? What is going to use them?

**Comment by akosmaroy** [comment]
Indeed, I didn't read up on the documentation. Apologies.
