### ISSUE TITLE
sh - command not found?

### ISSUE THREAD

**Issue by Wololon** [IbcAlpha/IBC#3]
Ubuntu 16.04, everything put in default directories. Getting "command not found" on the gatewaystart.sh file, any takes on this?

**Comment by rlktradewright** [comment]
Please attach the log file.

**Comment by rlktradewright** [comment]
In that case, the only explanations I can think of are:

1. The `/opt/ibc/scripts` folder is missing.
2. IBC_PATH is not set correctly in gatewaystart.sh
