### ISSUE TITLE
What setting to change for upgrading from 963 to 974?

### ISSUE THREAD

**Issue by oemGitHub** [IbcAlpha/IBC#31]
Once 963 is uninstalled and 974 is installed, I change following setting, which is able to launch 974 gateway, but not able to input those saved username and password for logon.
I would like to know on which setting and files should be changed.

Does anyone have any suggestions?
Thanks in advance for any suggestions

**File : C:\StartGateway.bat**
**set TWS_MAJOR_VRSN=974**
set CONFIG=%HOMEDRIVE%%HOMEPATH%\Documents\IBC\config.ini
set TRADING_MODE=paper
set IBC_PATH=%SYSTEMDRIVE%\IBC
set TWS_PATH=%SYSTEMDRIVE%\Jts
set LOG_PATH=%IBC_PATH%\Logs
set TWSUSERID=
set TWSPASSWORD=
set FIXUSERID=
set FIXPASSWORD=
set JAVA_PATH=
set HIDE=

**Comment by rlktradewright** [comment]
Have you upgraded your IBC to version 3.7.3?

https://github.com/IbcAlpha/IBC/releases

**Comment by oemGitHub** [comment]
Thank you very much for suggestions (^v^)

**Comment by rlktradewright** [comment]
If this is now ok, please close the issue.
