### ISSUE TITLE
IBC with TWS 974 may ignore the TradingMode setting in config.ini

### ISSUE THREAD

**Issue by rlktradewright** [IbcAlpha/IBC#37]
If you set TradingMode=paper in your config.ini, you may find that login doesn’t succeed, particularly if this is the first time you’ve tried paper trading mode. This is due to a change in the TWS login dialog that causes IBC to fail to find the relevant toggle buttons, so it can’t set the trading mode as per the config.ini. In this case, TWS just uses whatever setting it finds in jts.ini: if you’ve run paper trading before, this is likely to already be tradingMode=p, so you won’t notice any problem.

The Gateway is fine.

I’ve fixed this, but haven’t yet issued another release. I’ll probably do that later tonight.

**Comment by hbfff** [comment]
Hi Richard,

Sorry for such a novice question - I was wondering how I can implement the above fix. 

I have IBC 3.7.3 installed using the command:
`wget https://github.com/IbcAlpha/IBC/releases/download/3.7.3/IBCLinux-3.7.3.zip`

Both IBC and TWS .ini config files have been modified to indicate the paper trading mode; however, when running the script it still tries to login to a live session.

Additionally, I have tried
'wget https://github.com/IbcAlpha/IBC/releases/download/3.7.3-beta/IBCLinux-3.7.3-beta.zip'

I would have thought I need to adjust the source code and recompile the jar file, but unfortunately have no experience doing so.

If you would be able to suggest how I may implement the above fix, that would be greatly appreciated. 

Sorry for the somewhat IBC unrelated question.

Thanks.

**Comment by rlktradewright** [comment]
Apologies, I still haven't got round to issuing a new release for this. I will try to do so soon, but it probably won't be today.

However the fix at aed55f8 actually includes a compiled `IBC.jar` and the corresponding `version` file, so all you need to do is download these and replace the existing files in your ibc folder:

https://github.com/IbcAlpha/IBC/blob/master/resources/IBC.jar

https://github.com/IbcAlpha/IBC/blob/master/resources/version

**Comment by hbfff** [comment]
Thank you, I appreciate it!

**Comment by dqii** [comment]
Just wondering, was this fixed?

**Comment by dqii** [comment]
I saw that you fixed this about a month ago in the recent release. Thank you so much :)
