### ISSUE TITLE
IBC doesn't work with TWS 974.4g Login

### ISSUE THREAD

**Issue by heikohaensel** [IbcAlpha/IBC#39]
I'm using IBC 3.7.3 with the Latest Offline TWS 974.4g from Dec 18, but it doesn't work.
IBC is raising an error message, because it can't find the Use/store settings on server control in the login screen.
The IBC Log file contains the following messages:

================================================================================

This log file is located at:

    C:\IBC\Logs\IBC-3.7.3_TWS-974_MONDAY.txt

================================================================================

Starting IBC version 3.7.3 on Mon 01/07/2019 at 17:00:27.57

Operating system:  Microsoft Windows Server 2016 Datacenter  64-bit          10.0.14393  

Arguments:

TWS version = 974
Entry point = ibcalpha.ibc.IbcTws
/TwsPath = C:\Jts
/IbcPath = C:\IBC
/Config = C:\IBC\config.ini
/Mode = 
/JavaPath = 
/User =
/PW =
/FIXUser =
/FIXPW =

=================================

Generating the classpath
Classpath=C:\Jts\974\jars\jts4launch-974.jar;C:\Jts\974\jars\locales.jar;C:\Jts\974\jars\log4j-api-2.5.jar;C:\Jts\974\jars\log4j-core-2.5.jar;C:\Jts\974\jars\total-2018.jar;C:\Jts\974\jars\twslaunch-974.jar;C:\Jts\974\jars\twslaunch-install4j-1.9.jar;C:\IBC\IBC.jar

Generating the JAVA VM options
Java VM Options= -Xmx768m -XX:+UseG1GC -XX:MaxGCPauseMillis=200 -XX:ParallelGCThreads=20 -XX:ConcGCThreads=5 -XX:InitiatingHeapOccupancyPercent=70 -Dinstaller.uuid=c49f19ed-353e-4f27-83a6-132409f2de73 -DvmOptionsPath=C:\Jts\974\tws.vmoptions -Dsun.awt.nopixfmt=true -Dsun.java2d.noddraw=true -Dswing.boldMetal=false -Dsun.locale.formatasdefault=true

Determining the location of java.exe 
Location of java.exe=c:\program files\common files\i4j_jres\1.8.0_152\bin

Starting IBC with this command:
"c:\program files\common files\i4j_jres\1.8.0_152\bin\java.exe" -cp  "C:\Jts\974\jars\jts4launch-974.jar;C:\Jts\974\jars\locales.jar;C:\Jts\974\jars\log4j-api-2.5.jar;C:\Jts\974\jars\log4j-core-2.5.jar;C:\Jts\974\jars\total-2018.jar;C:\Jts\974\jars\twslaunch-974.jar;C:\Jts\974\jars\twslaunch-install4j-1.9.jar;C:\IBC\IBC.jar"  -Xmx768m -XX:+UseG1GC -XX:MaxGCPauseMillis=200 -XX:ParallelGCThreads=20 -XX:ConcGCThreads=5 -XX:InitiatingHeapOccupancyPercent=70 -Dinstaller.uuid=c49f19ed-353e-4f27-83a6-132409f2de73 -DvmOptionsPath=C:\Jts\974\tws.vmoptions -Dsun.awt.nopixfmt=true -Dsun.java2d.noddraw=true -Dswing.boldMetal=false -Dsun.locale.formatasdefault=true ibcalpha.ibc.IbcTws "C:\IBC\config.ini"  

2019-01-07 17:00:28:783 IBC: Properties file C:\Users\Administrator\Documents\IBC\config.ini not found
System Properties
------------------------------------------------------------
swing.boldMetal = false
java.runtime.name = Java(TM) SE Runtime Environment
sun.boot.library.path = c:\program files\common files\i4j_jres\1.8.0_152\bin
java.vm.version = 25.152-b16
sun.awt.nopixfmt = true
vmOptionsPath = C:\Jts\974\tws.vmoptions
java.vm.vendor = Oracle Corporation
java.vendor.url = http://java.oracle.com/
path.separator = ;
java.vm.name = Java HotSpot(TM) 64-Bit Server VM
file.encoding.pkg = sun.io
user.country = US
user.script = 
sun.java.launcher = SUN_STANDARD
sun.os.patch.level = 
java.vm.specification.name = Java Virtual Machine Specification
user.dir = C:\Jts
java.runtime.version = 1.8.0_152-b16
java.awt.graphicsenv = sun.awt.Win32GraphicsEnvironment
java.endorsed.dirs = c:\program files\common files\i4j_jres\1.8.0_152\lib\endorsed
os.arch = amd64
java.io.tmpdir = C:\Users\ADMINI~1\AppData\Local\Temp\2\
line.separator = 

java.vm.specification.vendor = Oracle Corporation
user.variant = 
os.name = Windows Server 2016
sun.java2d.noddraw = true
sun.jnu.encoding = Cp1252
java.library.path = c:\program files\common files\i4j_jres\1.8.0_152\bin;C:\Windows\Sun\Java\bin;C:\Windows\system32;C:\Windows;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Users\Administrator\AppData\Local\Microsoft\WindowsApps;;.
java.specification.name = Java Platform API Specification
java.class.version = 52.0
sun.management.compiler = HotSpot 64-Bit Tiered Compilers
os.version = 10.0
user.home = C:\Users\Administrator
user.timezone = Europe/Berlin
installer.uuid = c49f19ed-353e-4f27-83a6-132409f2de73
java.awt.printerjob = sun.awt.windows.WPrinterJob
file.encoding = Cp1252
java.specification.version = 1.8
java.class.path = C:\Jts\974\jars\jts4launch-974.jar;C:\Jts\974\jars\locales.jar;C:\Jts\974\jars\log4j-api-2.5.jar;C:\Jts\974\jars\log4j-core-2.5.jar;C:\Jts\974\jars\total-2018.jar;C:\Jts\974\jars\twslaunch-974.jar;C:\Jts\974\jars\twslaunch-install4j-1.9.jar;C:\IBC\IBC.jar
user.name = Administrator
java.vm.specification.version = 1.8
sun.java.command = ibcalpha.ibc.IbcTws C:\IBC\config.ini
java.home = c:\program files\common files\i4j_jres\1.8.0_152
sun.arch.data.model = 64
user.language = en
java.specification.vendor = Oracle Corporation
awt.toolkit = sun.awt.windows.WToolkit
java.vm.info = mixed mode
java.version = 1.8.0_152
java.ext.dirs = c:\program files\common files\i4j_jres\1.8.0_152\lib\ext;C:\Windows\Sun\Java\lib\ext
sun.boot.class.path = c:\program files\common files\i4j_jres\1.8.0_152\lib\resources.jar;c:\program files\common files\i4j_jres\1.8.0_152\lib\rt.jar;c:\program files\common files\i4j_jres\1.8.0_152\lib\sunrsasign.jar;c:\program files\common files\i4j_jres\1.8.0_152\lib\jsse.jar;c:\program files\common files\i4j_jres\1.8.0_152\lib\jce.jar;c:\program files\common files\i4j_jres\1.8.0_152\lib\charsets.jar;c:\program files\common files\i4j_jres\1.8.0_152\lib\jfr.jar;c:\program files\common files\i4j_jres\1.8.0_152\classes
java.vendor = Oracle Corporation
file.separator = \
java.vendor.url.bug = http://bugreport.sun.com/bugreport/
sun.io.unicode.encoding = UnicodeLittle
sun.cpu.endian = little
sun.desktop = windows
sun.locale.formatasdefault = true
sun.cpu.isalist = amd64
------------------------------------------------------------
2019-01-07 17:00:28:799 IBC: Using default settings provider: ini file is C:\IBC\config.ini
2019-01-07 17:00:28:799 IBC: Using default login manager: getting username and password from args but not found. Will get from settings
2019-01-07 17:00:28:799 IBC: Using default main window manager: constructor parameter isGateway=false
2019-01-07 17:00:28:799 IBC: Using default trading mode manager: constructor parameter args but trading mode not present - will be taken from settings
2019-01-07 17:00:28:808 IBC: Using default config dialog manager
2019-01-07 17:00:28:816 IBC: CommandServer is not started because the port is not configured
2019-01-07 17:00:29:156 IBC: TWS Settings directory is: C:\Jts
2019-01-07 17:00:29:162 IBC: Ensuring C:\Jts\jts.ini contains required minimal lines
2019-01-07 17:00:29:166 IBC: Found section: [Logon]
2019-01-07 17:00:29:166 IBC: Can't find setting: s3store=false
2019-01-07 17:00:29:166 IBC: Found section: [Logon]
2019-01-07 17:00:29:166 IBC: Found setting: s3store=true
2019-01-07 17:00:29:166 IBC: Found section: [IBGateway]
2019-01-07 17:00:29:166 IBC: Found setting: ApiOnly=true
2019-01-07 17:00:29:166 IBC: Confirmed C:\Jts\jts.ini contains required minimal lines
2019-01-07 17:00:37:156 IBC: Detected frame entitled: Login; event=Activated
2019-01-07 17:00:37:170 IBC: Detected frame entitled: Login; event=Opened
2019-01-07 17:00:37:171 IBC: Trading mode from settings: tradingMode=live
2019-01-07 17:00:37:172 IBC: Setting Trading mode = live
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
2019-01-07 17:00:37:174 IBC: Could not login: could not find control: Use/store settings on server
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

TWS finished at Mon 01/07/2019 17:00:37.87

**Comment by rlktradewright** [comment]
Well, it works fine for me with TWS 974.4g. So we'll have to gather some diagnostic information to see why it's not finding the checkbox when you run it.

Change the LogComponents setting in config.ini (right at the end) to:

`LogComponents=open`

and then run IBC again. This will cause the login dialog's structure to be recorded in the log file.

Then attach the logfile to your reply - please don't quote the logfile, attach it using the 'Attach files by dragging & dropping or selecting them' link at the bottom of the comment box.

By the way, you appear to be running IBC under the local administrator account. IBC runs just fine under a non-privileged account, and I strongly advise you to do it like that.

**Comment by heikohaensel** [comment]
Hi, 
looking at the log file after starting IBC with the changed settings I got an idea for the root cause of this issue. I had setup the language in the TWS to "German". This makes the IBC not finding the control. After I changed the language in TWS back to "English" I ran IBC again and voila it came up without errors now.

So I'm not sure if IBC supports other TWS languages than English.

**Comment by rlktradewright** [comment]
Yes that's right. IBC only supports English. It will work fine with the operating system set to other locales than English, but TWS itself must be run in English. I believe this is mentioned somewhere in the User Guide.

Interestingly, the TWS jar files actually include a file (locales.jar) that has all the translations of all the TWS strings into all the languages that TWS supports, and in principle it would be possible for IBC to use this file to support any of these languages. However I've never been able to justify the effort involved in doing this, since most people seem to be able to work quite adequately with the English version. It should be pretty straightforward to do this, so perhaps one day....
