### ISSUE TITLE
Gateway exits - unexistent error message

### ISSUE THREAD

**Issue by Wololon** [IbcAlpha/IBC#4]
Running into some issues with odd exits at random times - i.e. no exit at HH:MM set. 

All I can deduce from the log is the following:

/home/jo/opt/ibc/scripts/ibcstart.sh: line 428:  6258 Killed                  "$java_path/java" -cp "$ibc_classpath" $java_vm_options $entry_point "$ibc_ini" ${mode}
Gateway finished

The IB log weren't giving anything further information either. 

Any takes on these? I am missing the obvious?

**Comment by prurph** [comment]
@Wololon did you uncover anything more about this? I'm also noticing similar issues--IBC was running flawlessly for weeks (Mac OS X laptop) and lately overnight it somehow just seems to die.
