### ISSUE TITLE
Handling single popup

### ISSUE THREAD

**Issue by flgdev** [IbcAlpha/IBC#46]
So Im just trying to create my own tool to handle relogin popup, I dont need whole IBC functionality. Sorry for being lazy and not reading IBC and Swing docs, but I have a few questions to sort things out

1. How AWTEventListener is able to listen events from other application's windows? Is it because they were started from IBC?

2. what is this line about? I dont see any import or variable or whatever with name ibgateway as well as GWClient

`ibgateway.GWClient.main(twsArgs);`

**Comment by rlktradewright** [comment]
Well, my advice would be not to reinvent the wheel and just use IBC. What does it matter if you're not going to use the full functionality? IBC is tiny, and practically zero overhead. In my opinion, you need a good reason not to just use it as it is. Do you have such a reason?

I don't want to have to spend my time answering questions about how it works if you're not going to be using it. But on this occasion I'll answer the questions you asked:

1. It can't listen to events from other applications' windows, only from the current process. IBC loads TWS/Gateway into the IBC process, so both IBC and TWS/Gateway are running in the same process.

2. `ibgateway.GWClient.main()` is the entry point into the Gateway. It's in one of the jar files that are put in the jars folder when you install TWS/Gateway (probably `jts4launch-974.jar` but I'd need to check to be sure). `ibgateway.GWClient` is a class within this jar, and it has a `main` method like any other top-level Java entrypoint. You have to ensure your Java IDE has a reference to this jar in your project: how this needs to be done will depend on which IDE you're using. 

If this information is not enough to get you on your way, then you 're probably not going to succeed unless you spend the time understanding the AWT mechanisms: I'm not here to teach you!
