### ISSUE TITLE
v 3.8.1 ExistingSessionDetectedAction

### ISSUE THREAD

**Issue by jamiehyun** [IbcAlpha/IBC#54]
Hi, IBC is not able to auto-connect when the login is switched from desktop-IBC to IOS app. I have played around with the ExistingSessionDetectedAction setting but not getting consistent results. Ideally, I would want IBC to auto-click 'Disconnect the other session', when the login is switched to IOS app

**Comment by rlktradewright** [comment]
I'm sorry to hear that. Unfortunately I don't have an IOS device to test against, so this is all a bit hit-and-miss.

I'll need additional information to try and diagnose what's going on here. Could you please shut down IBC and set :

`ExistingSessionDetectedAction=primary`

`LogComponents=yes`

in your config.ini (LogComponents is the last setting in the file). 

Then delete the current log files, run IBC again, and login to your IOS app. Then attach the new logfile to your reply (**please ATTACH it,  don't just quote the contents** of the log file, which will be quite large).

**Comment by jamiehyun** [comment]
Log file attached.

There should be 2 login attempts from the IOS app; In the first instance, IBC correctly logged back in, but on the second instance, it was not able to deal with a pop up window which required manual input from the user

[IBC-3.8.1_TWS-976_THURSDAY.txt](https://github.com/IbcAlpha/IBC/files/3287808/IBC-3.8.1_TWS-976_THURSDAY.txt)

**Comment by rlktradewright** [comment]
Ok, thanks for that info.

It seems that when two-factor authentication is involved, there is an additional dialog that IBC needs to deal with, the 'Trading Login Handoff' dialog. (I don't use 2FA for TWS logins, so I've not come across this before).

That should be easy enough to deal with.  All the information I need to recognise the dialog is in the log file, and clicking either the 'Transfer Authentication To Other session' button or 'Disconnect Other Session' button or 'Exit Application' button depending on the `ExistingSessionDetectedAction` setting is straightforward.

It's getting late here in the UK now, so I won't try to do this tonight, but hopefully I'll be able to give you a new version to test tomorrow.

**Comment by jamiehyun** [comment]
Fantastic, thank you very much for undertaking this project!

Cheers

**Comment by rlktradewright** [comment]
I've implemented an initial version, and a zip is attached. You'll just need to copy the `IBC.jar` and `version` files into your IBC folder, to replace the existing ones.

If you don't mind, it would be very helpful if you could test this with both TWS and the Gateway, and with both `ExistingSessionDetectedAction=primary` and `ExistingSessionDetectedAction=primaryoverride`: the latter should allow the IOS session to proceed, and should take it back again if you then restart IBC.

[IBCWin-3.8.2-beta.1.zip](https://github.com/IbcAlpha/IBC/files/3290516/IBCWin-3.8.2-beta.1.zip)

**Comment by jamiehyun** [comment]
I was able to test the beta version on TWS only (I do not have access to the Gateway) and here are my findings when logging in from an IOS app whilst IBC is running:


1)      ExistingSessionDetectedAction=primary

·         Login from IOS app successful. IBC re-initiates login from the primary session (requires re-authentication for 2 factor) and the IOS session is disconnected


2)      ExistingSessionDetectedAction=primaryoverride

·         Login from IOS app successful. IBC closes the primary session. IOS session is maintained. Not sure if this is what is intended

All in all, the beta version does what I want with ‘primary’ setting above, which is for IBC to re gain control of the primary after a temporary login from an IOS app.

Apologies for the delay and keep up the good work!

**Comment by rlktradewright** [comment]
Thanks for that. What you report is exactly what I expected. Actually it's better than what I expected because I hadn't appreciated before that once you've logged in to the mobile app, you can hold off completing the 2FA-reauthentication on the primary until you've finished on the mobile app. Do you know if there's a time limit on the 2FA?

Using `ExistingSessionDetectedAction=primaryoverride` is only really useful if you need to be able to use the mobile app or the client portal with market data, and don't use 2FA. In such circumstances   `ExistingSessionDetectedAction=primary` is no help because it will immediately take the session back as soon as you login on the mobile app or client portal.

**Comment by jamiehyun** [comment]
There does not seem to be a set time limit on the 2FA. It seems to vary depending on the session.

I have been using the beta for the past week or so and it is working wonderfully!

**Comment by rlktradewright** [comment]
I'm glad to hear that it's working well. 

I must get round to doing the official release...

**Comment by rlktradewright** [comment]
At long last, this update has been included in Release 3.8.2
