### ISSUE TITLE
Where to enable SSL on script during login?

### ISSUE THREAD

**Issue by oemGitHub** [IbcAlpha/IBC#55]
I would like to know on where to enable SSL on script during login and which file should be edited.

Does anyone have any suggestions?
Thanks in advance for any suggestions

**Comment by rlktradewright** [comment]
You can't use IBC to automatically set the `Use SSL` checkbox when logging in.

Here's how to do it manually:

1. Open `config.ini` in a text editor..
2. Comment out the `IbPassword` line. (put a `#` at the start of the line) and save the file.
3. Run IBC.
4. At the login dialog, set `Use SSL` as required. 
5. Enter your password.
6. Complete the login.
7. Edit `config.ini` to remove the comment.

Now the `Use SSL` checkbox will be set every time you start IBC, until you manually clear it.

Another way to do it is to locate the `Jts.ini` file in your TWS settings directory. Make sure it includes the line:

`UseSSL=true`

in the `[Logon]` section.

By the way, it appears that Gateway no longer offers an SSL option starting with (I think) Gateway 974. I presume it just always uses SSL.

**Comment by oemGitHub** [comment]
Thank you very much for suggestions (^v^)

**Comment by ValeryNo** [comment]
Just in case someone else bumps into this - my IB Gateway failed to start today on a server with this
![2021-08-24_08-39-26](https://user-images.githubusercontent.com/6953938/130649600-d8dfa907-d1e3-4ed3-b2d3-f6167314c525.png)

I removed obsolete SSL settings from config.ini and realized jts.ini still had UseSSL=false, must have been set years ago. So it stopped working today and fix was setting it to true (deleting all-together might to the same)

**Comment by rlktradewright** [comment]
This topic is addressed in #133.

Please no-one add anything more to this issue.
