### ISSUE TITLE
Run dos2unix on config.ini before bundling the Linux release?

### ISSUE THREAD

**Issue by meteorpublish** [IbcAlpha/IBC#58]
Right now the CRs look ugly.

Running `dos2unix` is also mentioned in [this guide](https://dimon.ca/how-to-setup-ibc-and-tws-on-headless-ubuntu-in-10-minutes/).

**Comment by rlktradewright** [comment]
Only if you use something like vi to edit the file. vim is fine, gedit is fine, and I suspect most text editors these days will handle both Windows and Unix line endings without problems. Heck, even Notepad on Windows 10 now copes with Unix line endings (though curiously it doesn't seem to have a way of controlling the line endings). 

I consider this a non-issue, and don't want to spend any time on it, but feel free to convince me I'm wrong!

And if you want to provide an enhancement to the build script to run `dos2unix` before creating the zip, you're welcome to submit a pull request.
