### ISSUE TITLE
Any zip file to download IBC?

### ISSUE THREAD

**Issue by oemGitHub** [IbcAlpha/IBC#6]
I would like to know on any zip file to download IBC or do I need to download one by one?

Does anyone have any suggestions?
Thanks in advance for any suggestions

**Comment by rlktradewright** [comment]
That error message is very clear. It's telling you that config.ini does not exist, and it's telling you where it expects to find it. So just make sure it's in the correct place.

It's absolutely nothing to do with %IBC_PATH%. The error actually occurs in StartIBC.bat, at this line:

```
) else if not exist "%CONFIG%" (
	set ERROR_MESSAGE=IBC configuration file: %CONFIG%  does not exist
```

IBC is _very_ easy to set up. There are detailed instructions in the User Guide. Make sure you've read them! In particular, make sure you read and understand the section near the end of the User Guide that details the differences between IBC and IBController. And don't try to 'convert' an IBController installation into an IBC installation - they are not the same thing.

**Comment by oemGitHub** [comment]
Referring to following coding, there is error as **shown below**
**%IBC_PATH%** is not set for this variable within DisplayBannerAndLaunch.bat, so it gets error on not able to find version.  I would like to know on how %IBC_PATH% gets value from another ini file under this statement.

Do you have any suggestions?
Thank you very much for any suggestions (^v^)

**C:\IBC\scripts\DisplayBannerAndLaunch.bat**
@echo off
setlocal enableextensions enabledelayedexpansion

call :SetScreenColors %1, **which cannot be found.**

:: get the IBC version

for /f "tokens=1 delims=" %%i in (**%IBC_PATH%**\version) do set IBC_VRSN=%%i
echo %IBC_PATH%

**Comment by rlktradewright** [comment]
No, there is not a coding error. 

To start IBC you need to run the StartGateway.bat or StartTWS.bat files in the C:\IBC folder. DON@T try running DisplayBannerAndLaunch.bat or StartIBC.bat in the Scripts folder: they are called automatically from StartGateway.bat or StartTWS.bat, and they supply the variables that you are unable to locate. 

:SetScreenColors is a subroutine which you'll find at the end of DIsplayBannerAndLaunch.bat, but again you don't need to know that.

Listen, do yourself a favour, READ THE USER GUIDE!!!, and follow the very simple instructions it contains. It really couldn't be any simpler! Why should I keep wasting my time on you when you won't follow instructions?

**Comment by oemGitHub** [comment]
Referring to the userguide,  (Protecting the Password in the Password Security section) cannot be located as shown below:

4. Create an encrypted folder called IBC in your personal filestore (**see Protecting the Password
in the Password Security section**).

Do you have any suggestions on where to find this section?
Thank you very much for any suggestions (^v^)
