### ISSUE TITLE
Allow read-only access

### ISSUE THREAD

**Issue by mechspace** [IbcAlpha/IBC#61]
![image](https://user-images.githubusercontent.com/22416926/62831397-cdd77100-bc1e-11e9-8ef0-8f397baa193e.png)

Add an option to config.ini choose Read-only access.

**Comment by rlktradewright** [comment]
There is already such an option: ReadOnlyLogin

If this is not what you need, please explain your use case in more detail.

**Comment by mechspace** [comment]
I see, you are right. I overlooked this option.
