### ISSUE TITLE
No issue- just Clarification needed

### ISSUE THREAD

**Issue by Traderbaker** [IbcAlpha/IBC#62]
Hi i have downloaded IBC and it works great , thanks very much.

i am a single user and when  its connected, the gateway  shows multiple Clients , is this normal ? or should it only show 1 client (me)  i just wanted to clarify

![gateway](https://user-images.githubusercontent.com/54070807/62948568-7f6fd100-bddc-11e9-99b3-7a848e53c8ba.png)

**Comment by rlktradewright** [comment]
Nothing that the Gateway displays has anything to do with IBC, so you'd see exactly the same thing if you weren't using IBC.

These are presumably clientIDs that you've used at some point in the past. I don't know how long Gateway remembers them for.

Certainly nothing to be concerned about.

**Comment by Traderbaker** [comment]
Perfect, thanks a lot - i appreciate the response and the great work :)
