### ISSUE TITLE
Google Cloud installation: Error: xterm: xt error can't open display xterm display is not set

### ISSUE THREAD

**Issue by neilsmurphy** [IbcAlpha/IBC#64]
I am trying to transition an installation using IBC from my local machine to Google Cloud server. (also tried this in AWS, same problem). 

IBC works fine on my local machine launching TWS no problem. 

I’ve reinstalled the same settings and software to an Ubuntu 18 remote server and keep getting: 

`xterm: xt error can't open display xterm display is not set`

I’m using ubuntu-1804-bionic with 8g ram and 20g hard storage. IBC is installed in root directory /opt/ibc/. config.ini is in ~/ibc/ and is properly referrenced in TWSStart.sh. 

I’m using IBCLinux-3.8.1 and tws-stable-standalone-linux-x64.sh. 

I’m running Ubuntu 18.04.3 LTS locally as well. 

If I try to run 

`DISPLAY=:0 /opt/ibc/twsstart.sh`

I get no output, just a new command line. Or the above mentioned error.

If I run 

`~$ xterm `

from the remote terminal, a terminal window pops up.  

I have used vncserver and vncviewer to view the server desktop and can launch TWS from there.

I’m sure I’m missing something simple. 

Thank you for taking the time to read and help. Please let me know if I can supply better information.

**Comment by rlktradewright** [comment]
You probably just need to install a virtual frame buffer like xvfb.

I recommend you read Dmitry Shevkoplyas' very helpful guide at: https://dimon.ca/how-to-setup-ibc-and-tws-on-headless-ubuntu-in-10-minutes/

**Comment by neilsmurphy** [comment]
@rlktradewright Thank you very much. Apparently, you can't take short cuts Dmitry's guide. Cheers,

**Comment by dhgclt** [comment]
https://github.com/dhgclt/xterm-fix-for-kali-nethunter/blob/main/README.md
