### ISSUE TITLE
Which files are required to change for updating TWS API?

### ISSUE THREAD

**Issue by oemGitHub** [IbcAlpha/IBC#66]
I need to upgrade TWS API version, and would like to know on which files are required to change for IBC in order to recognize the new version of TWS API.

Does anyone have any suggestions?
Thanks in advance for any suggestions

**Comment by rlktradewright** [comment]
You only need to change the StartTws.bat and StartGateway.bat files (or twsstart.sh and gatewaystart.sh on Linux/macOS). The only line in these files you need to change is the one that says:

set TWS_MAJOR_VRSN=972

If you're moving to TWS 976,for example, then change it to:

set TWS_MAJOR_VRSN=976
