### ISSUE TITLE
"Enter security code" Issue

### ISSUE THREAD

**Issue by memoryfraction** [IbcAlpha/IBC#69]
When I use IBC to autostart the IB Controller, I found there is a notice as below.
Question is, how to select "Enter Read Only" automatically?

![无标题](https://user-images.githubusercontent.com/18358791/71391377-83510280-25c9-11ea-8a60-9329ae3b58ae.png)

**Comment by rlktradewright** [comment]
Doesn't 

`ReadOnlyLogin=yes`

in `config.ini` give you what you want?

**Comment by memoryfraction** [comment]
Thanks, problem solved
