### ISSUE TITLE
Anyone else having TWS freeze at start when paper trading?

### ISSUE THREAD

**Issue by hokavs** [IbcAlpha/IBC#70]
Hi,

I'm running TWS 976, and while paper trading it regularly freezes on startup (around the same time it is supposed to acknowledge that pop-up box about TWS being in paper trading mode). 

My question is: does anybody else have this problem? And could we perhaps introduce a timer/delay for agreeing to this popup box, which might prevent TWS from freezing alltogether at boot (whilst in paper trading mode) ? Java is not the problem, as I re-installed it and also switched servers. CPU and memory are also not the problem. And I'm running the latest IBC version.

Merry christmas to all!

Kind regards,

Hendrik

**Comment by rlktradewright** [comment]
Attach (don't quote) your IBC log file so we can see if it contains anything helpful.

**Comment by hokavs** [comment]
No problem. Here's the log from today. Around 22:08 TWS froze again after reboot.

[IBC-3.8.1_TWS-976_THURSDAY.txt](https://github.com/IbcAlpha/IBC/files/4004010/IBC-3.8.1_TWS-976_THURSDAY.txt)

**Comment by rlktradewright** [comment]
This line seems suspicious:

`2019-12-26 22:06:18:587 IBC: Ensuring C:\Jts976\\jts.ini contains required minimal lines`

It shouldn't contain a double backslash in the filename.

Have you got `IbDir` set in config.ini? If so can you make sure it's correct: it should say

`IbDir=C:\\Jts976`

**Comment by hokavs** [comment]
Seems like that fixed that

**Comment by hokavs** [comment]
Hi there,

I am still experiencing issues when paper trading with IBC. I suspect it has something to do with the popup at start, which either fails to load, or IBC tries to "click it" too fast and it makes TWS stuck. When I log in manually (also on paper trading account), there is no issue whatsoever. 

Hope someone can help me. Let me know which info I need to share. Thanks in advance..

**Comment by rlktradewright** [comment]
I'd like to see the logfile, the config.ini and the StartTWS.bat (make sure you remove the username and password from the config.ini). Attach the files.

**Comment by rlktradewright** [comment]
Oh, I mean the IBC logfile, not the TWS one.
