### ISSUE TITLE
how to re-login automatically?

### ISSUE THREAD

**Issue by memoryfraction** [IbcAlpha/IBC#71]
Got below notice, wondering how to re-login automatically?
![无标题](https://user-images.githubusercontent.com/18358791/71495004-13cd5400-2811-11ea-929e-8c4554354ad4.png)

**Comment by rlktradewright** [comment]
Use the latest version 3.8.0, which handles this automatically.

Download the zip file and extract just the `IBC.jar` and `version` files, overwriting your existing copies.
