### ISSUE TITLE
IB Gateway does not log in

### ISSUE THREAD

**Issue by ronnyli** [IbcAlpha/IBC#86]
[ibc-3.8.2_GATEWAY-978_Sunday.txt](https://github.com/IbcAlpha/IBC/files/4499625/ibc-3.8.2_GATEWAY-978_Sunday.txt)

Hi, I had IBC working perfectly until a few days ago. Now it fills in my username and password but doesn't log in to IB. Manually clicking the Log In button doesn't do anything either.

In the attached logs I noticed that the Paper Log In button has been disabled but I'm not sure what the reason is or how to fix it.

Any advice would be appreciated. Thanks!

**Comment by rlktradewright** [comment]
Well, it looks like IBC has done what it's supposed to do but the Gateway isn't responding. Perhaps there's a problem at IB?

Have you tried running the Gateway manually, ie not using IBC? Can you login successfully there?

If not, just try again later.

**Comment by ronnyli** [comment]
Thanks for the quick response @rlktradewright!

Manually logging in to IB Gateway on my laptop works and so does logging into the client portal which made me think that the issue was due to how I configured IBC. This has been the case for the past few days so I thought I'd ask here for advice.

**Comment by rlktradewright** [comment]
Please could you explain how you resolved the problem?

**Comment by ronnyli** [comment]
Sure thing. Switching from the latest IB Gateway to stable solved my problem. I had forked my IBC setup code from somewhere else so I didn't understand how it could be broken when the code was unchanged. I switched to stable after reading your user guide.
