### ISSUE TITLE
IBC does not fill user name and password 

### ISSUE THREAD

**Issue by real-ssdn** [IbcAlpha/IBC#90]
================================================================================

Arguments:

TWS version = 979
Entry point = ibcontroller.IBGatewayController
--tws-path = /root/Jts
--tws-settings-path = /root/Jts
--ibc-path = /root/IBController
--ibc-ini = /root/IBController/IBController.ini
--mode = 
--java-path = 
--user =
--pw =
--fix-user =
--fix-pw =

=================================
Generating the classpath
Classpath=/root/Jts/ibgateway/979/jars/jts4launch-979.jar:/root/Jts/ibgateway/979/jars/jxbrowser-7.5.jar:/root/Jts/ibgateway/979/jars/jxbrowser-linux64-7.5.jar:/root/Jts/ibgateway/979/jars/jxbrowser-swing-7.5.jar:/root/Jts/ibgateway/979/jars/locales.jar:/root/Jts/ibgateway/979/jars/log4j-api-2.5.jar:/root/Jts/ibgateway/979/jars/log4j-core-2.5.jar:/root/Jts/ibgateway/979/jars/total-2018.jar:/root/Jts/ibgateway/979/jars/twslaunch-979.jar:/root/Jts/ibgateway/979/jars/twslaunch-install4j-1.9.jar:/root/IBController/IBController.jar

Generating the JAVA VM options
Java VM Options=-Xmx768m -XX:+UseG1GC -XX:MaxGCPauseMillis=200 -XX:ParallelGCThreads=20 -XX:ConcGCThreads=5 -XX:InitiatingHeapOccupancyPercent=70

Determining the location of java executable
Location of java executable=/usr/local/i4j_jres/1.8.0_152-tzdata2019c/bin

Starting IBGateway with this command:
"/usr/local/i4j_jres/1.8.0_152-tzdata2019c/bin/java" -cp "/root/Jts/ibgateway/979/jars/jts4launch-979.jar:/root/Jts/ibgateway/979/jars/jxbrowser-7.5.jar:/root/Jts/ibgateway/979/jars/jxbrowser-linux64-7.5.jar:/root/Jts/ibgateway/979/jars/jxbrowser-swing-7.5.jar:/root/Jts/ibgateway/979/jars/locales.jar:/root/Jts/ibgateway/979/jars/log4j-api-2.5.jar:/root/Jts/ibgateway/979/jars/log4j-core-2.5.jar:/root/Jts/ibgateway/979/jars/total-2018.jar:/root/Jts/ibgateway/979/jars/twslaunch-979.jar:/root/Jts/ibgateway/979/jars/twslaunch-install4j-1.9.jar:/root/IBController/IBController.jar" -Xmx768m -XX:+UseG1GC -XX:MaxGCPauseMillis=200 -XX:ParallelGCThreads=20 -XX:ConcGCThreads=5 -XX:InitiatingHeapOccupancyPercent=70 ibcontroller.IBGatewayController "/root/IBController/IBController.ini"  

System Properties
------------------------------------------------------------
java.runtime.name = Java(TM) SE Runtime Environment
sun.boot.library.path = /usr/local/i4j_jres/1.8.0_152-tzdata2019c/lib/amd64
java.vm.version = 25.152-b16
java.vm.vendor = Oracle Corporation
java.vendor.url = http://java.oracle.com/
path.separator = :
java.vm.name = Java HotSpot(TM) 64-Bit Server VM
file.encoding.pkg = sun.io
user.country = US
sun.java.launcher = SUN_STANDARD
sun.os.patch.level = unknown
java.vm.specification.name = Java Virtual Machine Specification
user.dir = /root/Jts
java.runtime.version = 1.8.0_152-b16
java.awt.graphicsenv = sun.awt.X11GraphicsEnvironment
java.endorsed.dirs = /usr/local/i4j_jres/1.8.0_152-tzdata2019c/lib/endorsed
os.arch = amd64
java.io.tmpdir = /tmp
line.separator = 

java.vm.specification.vendor = Oracle Corporation
os.name = Linux
sun.jnu.encoding = UTF-8
java.library.path = /usr/java/packages/lib/amd64:/usr/lib64:/lib64:/lib:/usr/lib
java.specification.name = Java Platform API Specification
java.class.version = 52.0
sun.management.compiler = HotSpot 64-Bit Tiered Compilers
os.version = 4.4.0-184-generic
user.home = /root
java.awt.printerjob = sun.print.PSPrinterJob
file.encoding = UTF-8
java.specification.version = 1.8
java.class.path = /root/Jts/ibgateway/979/jars/jts4launch-979.jar:/root/Jts/ibgateway/979/jars/jxbrowser-7.5.jar:/root/Jts/ibgateway/979/jars/jxbrowser-linux64-7.5.jar:/root/Jts/ibgateway/979/jars/jxbrowser-swing-7.5.jar:/root/Jts/ibgateway/979/jars/locales.jar:/root/Jts/ibgateway/979/jars/log4j-api-2.5.jar:/root/Jts/ibgateway/979/jars/log4j-core-2.5.jar:/root/Jts/ibgateway/979/jars/total-2018.jar:/root/Jts/ibgateway/979/jars/twslaunch-979.jar:/root/Jts/ibgateway/979/jars/twslaunch-install4j-1.9.jar:/root/IBController/IBController.jar
user.name = root
java.vm.specification.version = 1.8
sun.java.command = ibcontroller.IBGatewayController /root/IBController/IBController.ini
java.home = /usr/local/i4j_jres/1.8.0_152-tzdata2019c
sun.arch.data.model = 64
user.language = en
java.specification.vendor = Oracle Corporation
awt.toolkit = sun.awt.X11.XToolkit
java.vm.info = mixed mode
java.version = 1.8.0_152
java.ext.dirs = /usr/local/i4j_jres/1.8.0_152-tzdata2019c/lib/ext:/usr/java/packages/lib/ext
sun.boot.class.path = /usr/local/i4j_jres/1.8.0_152-tzdata2019c/lib/resources.jar:/usr/local/i4j_jres/1.8.0_152-tzdata2019c/lib/rt.jar:/usr/local/i4j_jres/1.8.0_152-tzdata2019c/lib/sunrsasign.jar:/usr/local/i4j_jres/1.8.0_152-tzdata2019c/lib/jsse.jar:/usr/local/i4j_jres/1.8.0_152-tzdata2019c/lib/jce.jar:/usr/local/i4j_jres/1.8.0_152-tzdata2019c/lib/charsets.jar:/usr/local/i4j_jres/1.8.0_152-tzdata2019c/lib/jfr.jar:/usr/local/i4j_jres/1.8.0_152-tzdata2019c/classes
java.vendor = Oracle Corporation
file.separator = /
java.vendor.url.bug = http://bugreport.sun.com/bugreport/
sun.io.unicode.encoding = UnicodeLittle
sun.cpu.endian = little
sun.cpu.isalist = 
------------------------------------------------------------
02:21:55:782 IBController: using default settings provider: ini file is /root/IBController/IBController.ini
02:21:55:784 IBController: using default login manager: getting username and password from args but not found. Will get from settings
02:21:55:787 IBController: using default config dialog manager: constructor parameter isGateway=true
02:21:55:788 IBController: using default trading mode manager: constructor parameter args but trading mode not present - will be taken from settings
02:21:55:792 IBController: using default config dialog manager
02:21:55:801 IBController: IBControllerServer is started.
02:21:55:804 IBController: IBControllerServer listening on address: 127.0.0.1 port: 7462
02:21:55:805 IBController: Gateway will be shut down at 2020/06/20 04:11
02:21:55:980 IBController: Ensuring /root/Jts/jts.ini contains required minimal lines
02:21:55:980 IBController: Found section: [Logon]
02:21:55:981 IBController: Can't find setting: s3store=false
02:21:55:981 IBController: Found section: [Logon]
02:21:55:981 IBController: Found setting: s3store=true
02:21:55:981 IBController: Found section: [IBGateway]
02:21:55:981 IBController: Found setting: ApiOnly=true
02:21:55:981 IBController: Confirmed /root/Jts/jts.ini contains required minimal lines
02:21:55:981 IBController: TWS settings directory is /root/Jts
02:22:01:259 IBController: detected frame entitled: IB Gateway; event=Activated
02:22:01:269 IBController: detected frame entitled: IB Gateway; event=Opened

**Comment by rlktradewright** [comment]
[_For future reference, please don't quote entire log files. Just attach them._]

IBController has been superseded by IBC more than two years ago. That's this repository, by the way, so you must surely have known this?

IBController does not work with versions of TWS/Gateway later than 972. 

So you will have to move to IBC. Use the latest version (currently 3.8.2). 

Make sure you read the User Guide, since there are some differences between IBC and IBController. There is a section on this at the end of the Guide.

**Comment by real-ssdn** [comment]
I am using IBC right now just folder name is IBController .. I've just extraced the IBC zip file in IBController folder...

**Comment by rlktradewright** [comment]
No you are using IBController!

Look at your log file:

Entry point = ibcontroller.IBGatewayController  WRONG!

End of classpath: /root/IBController/IBController.jar   WRONG!

Need I go on?

You need to set up IBC from scratch, not just extract the zip into the old IBController directory.

Please try harder!

**Comment by real-ssdn** [comment]
yes it was a mistake. tnx
