### ISSUE TITLE
Error:  does not exist - TWS 979

### ISSUE THREAD

**Issue by amirmansoubi828** [IbcAlpha/IBC#91]
Does your project support TWS 979?
What does this error show?

![ibc](https://user-images.githubusercontent.com/24829076/88489122-9c7ac100-cfa7-11ea-9cc7-f42f36847742.jpeg)

$ ls /opt/ibc/
config.ini  crontab.txt  gatewaystart.sh  IBC.jar  LICENSE.txt  README.txt  scripts  twsstart.sh  userguide.pdf  version
$ ls /home/amir/ibc/
config.ini  logs

**Comment by rlktradewright** [comment]
Yes it does work just fine with TWS979.

There are only two conditions that can cause this error message, and of these the only likely one is that the location you specified for JAVA_PATH is twsstart.sh (ie /usr/bin/java) doesn't actually contain a Java installation.

Why did you set this anyway? The notes in twsstart.sh make it very clear that you don't need to set this unless you have a very good reason, and I have yet to find ANY reason to set it, let alone a good one!

So leave that setting blank and see if that helps.

The other possible reason is that /home/amir/Jts doesn't contain the TWS installation.

**Comment by amirmansoubi828** [comment]
java-path was clear before it and the error was the same. Anyway, I cleared it again!
![image](https://user-images.githubusercontent.com/24829076/88515829-8994da80-d001-11ea-8d78-0a9d03aa2118.png)

$ ls /home/amir/Jts/979/
 jars  'Trader Workstation 979.desktop'   tws   uninstall

**Comment by rlktradewright** [comment]
There is a crucial file missing from your installation folder. Here's what you should have:

`$ ls /home/richard/Jts/979
 jars  'Trader Workstation 979.desktop'   tws   tws.vmoptions   uninstall`

The file tws.vmoptions is not in your folder. So uninstall TWS and re-install it. Make sure you download the latest version first - it's just possible that the version you installed had a broken installer, though this is exceedingly unlikely.

**Comment by amirmansoubi828** [comment]
Thanks a lot.
I re-installed and it solved the problem.
Thanks again.
