### ISSUE TITLE
Having trouble with MOO orders when using IBC

### ISSUE THREAD

**Issue by brcarey** [IbcAlpha/IBC#97]
MOO orders are MKT + tif=OPG - they work when I run TWS directly, but not when I use IBC. I can't seem to find what the difference is. Has anyone else come across this issue?

**Comment by rlktradewright** [comment]
There is no imaginable mechanism by which IBC could have any influence at all on how TWS processes orders.

You need to look elsewhere.

If you really want to insist that IBC is somehow involved in this, then you need to explain what you mean by 'MOO orders don't work'. What happens to them? Screenshots? Any kind of evidence?

But I guarantee that you are wasting your time (and mine) pursuing this line. Take it up with IB.

**Comment by brcarey** [comment]
You were 100% correct, dumb mistake on my part - my apologies.
