### ISSUE TITLE
Exciting new Paper Trading warning

### ISSUE THREAD

**Issue by dvasdekis** [IbcAlpha/IBC#98]
Looks like IB has suddenly implemented a new Paper Trading warning for me. See below:
![Image of warning](https://raw.githubusercontent.com/dvasdekis/images/master/new_paper_trading_warning.png)

All API connections are stopped while the warning is up. When I manually click accept, the warning disappears and life goes on.

I am using IBC 3.8.4 beta2, with Gateway 978.2f on Linux.

It looks like a different warning to that reported [here](https://github.com/IbcAlpha/IBC/issues/8).

Btw, thanks again RLK for all your awesome work! I'm sorry to bother you with such piddly issues.

**Comment by rlktradewright** [comment]
This popup has been there for years, and IBC has handled it ever since it was invented.

See the AcceptNonBrokerageAccountWarning setting in config.ini.

**Comment by dvasdekis** [comment]
You're right, that worked perfectly. 

Not sure why this screen only started showing for me now. Apologies!
